square/okio

- benchmarks/README.md
- benchmarks/pom.xml
- benchmarks/src/main/java/com/squareup/okio/benchmarks/BufferPerformanceBench.java
- okio/pom.xml
- pom.xml
As discussed in #94 here are some benchmarks so that we can discuss segment pool alternatives in server environments.
These microbenchmarks try to measure performance of common buffer operations in a request/response handling scenario and a multi-threaded server environment. There are two benchmarks:
- Hot: This is a "pedal-to-the-metal" test. It is not a realistic use of the buffers but it may be useful in finding out performance regressions that are otherwise too subtle to show up any other way.
- Cold: This test simulates request handling with a configurable think time between responses. It assumes request data is saved and queued as they arrive before they are rate-limited/expired and that response workers outnumber request handlers. I think these are reasonable assumptions based on …
> Add JMH benchmarks for measuring buffer performance.

- okio/src/main/java/okio/Buffer.java
- okio/src/main/java/okio/RealBufferedSink.java
- okio/src/test/java/okio/BufferedSinkTest.java
> Force write(Source, long) to write fully.

- okio/src/main/java/okio/Buffer.java
- okio/src/main/java/okio/ByteString.java
- okio/src/main/java/okio/DeflaterSink.java
- okio/src/main/java/okio/GzipSink.java
- okio/src/main/java/okio/InflaterSource.java
- okio/src/main/java/okio/Okio.java
- okio/src/main/java/okio/Segment.java
- okio/src/main/java/okio/SegmentPool.java
- okio/src/main/java/okio/SegmentedByteString.java
- okio/src/main/java/okio/Util.java
- okio/src/test/java/okio/BufferTest.java
- okio/src/test/java/okio/BufferedSinkTest.java
- okio/src/test/java/okio/BufferedSourceTest.java
- okio/src/test/java/okio/ByteStringTest.java
- okio/src/test/java/okio/GzipSinkTest.java
- okio/src/test/java/okio/SegmentSharingTest.java
- okio/src/test/java/okio/TestUtil.java
We now have three different types of segments:
* Private. This was the only type of segment previously offered.
This is shared=false, owner=true.
* Appendable. Segments of this type can be written, but only
beyond segment.limit. Bytes preceding segment.limit are shared
and must not be written. This is shared=true, owner=true.
* Unwritable. Segments of this type cannot be written at all.
They are owned by another buffer. This is shared=true, owner=false.
Note that there are no segments of type 'shared=false, owner=false',
since the only way a buffer doesn't own its segment is if that segment
is shared.
This introduces a new subclass of ByteString, SegmentedByteString.
These byte strings share backing arrays with buffers. SegmentedByteString
instances are immutable and support fast random …
> Segment sharing.

- okio/src/main/java/okio/DeflaterSink.java
- okio/src/main/java/okio/InflaterSource.java
- okio/src/main/java/okio/Okio.java
- okio/src/test/java/okio/DeflaterSinkTest.java
- okio/src/test/java/okio/InflaterSourceTest.java
With segment sharing it's important that we never have empty segments
around inside a buffer. These were some edge cases where that was
possible.
Closes https://github.com/square/okio/issues/129
> Make sure every writableSegment() call writes or recycles.

- okio/src/main/java/okio/RealBufferedSource.java
- okio/src/test/java/okio/BufferedSourceTest.java
Currently we crash while composing the NumberFormatException on the call
to get(0).
Closes: https://github.com/square/okhttp/issues/1540
> Throw EOFException reading digits from an empty source.

- okio/src/main/java/okio/Buffer.java
- okio/src/main/java/okio/BufferedSink.java
- okio/src/main/java/okio/BufferedSource.java
- okio/src/main/java/okio/RealBufferedSink.java
- okio/src/main/java/okio/RealBufferedSource.java
- okio/src/test/java/okio/BufferedSourceTest.java
- okio/src/test/java/okio/Utf8Test.java
The String APIs transcode UTF-16 to UTF-8 and back.
These APIs avoid the UTF-16 intermediate form altogether, and
go right from UTF-8 to a codepoint and back.
> APIs to read and write code points.

- okio/src/main/java/okio/ForwardingTimeout.java
- okio/src/main/java/okio/Timeout.java
Previously this was throwing IOException, but nothing was anticipated
that. This is slightly semantically incorrect; the thread wasn't
interrupted. But it's much more convenient to use a single exception
type for both timeouts.
Also add a new type, ForwardingTimeout.
> Change Timeout.throwIfReached() to throw InterruptedIOException

- okio/src/main/java/okio/AsyncTimeout.java
- okio/src/main/java/okio/Okio.java
- okio/src/test/java/okio/SocketTimeoutTest.java
...instead of InterruptedIOException. This is a backwards compatible
change because SocketTimeoutException extends
InterruptedIOException.
This change is to address:
https://github.com/square/okhttp/issues/1676
> Make Okio Socket-related methods throw SocketTimeoutException

- okio/src/main/java/okio/Buffer.java
This has the happy side-effect of preventing the Lenovo S939 from
behaving incorrectly when executing this method.
The following test exercises the previous code; it fails after
a few iterations on that device:
https://gist.github.com/swankjesse/4396e276e43dbb0e71cc
Unfortunately there's no good way to regression test that we
haven't hit a bug in a specific lousy device.
> Move a cast in Buffer.indexOf().

- okio/src/main/java/okio/AsyncTimeout.java
- okio/src/main/java/okio/Okio.java
- okio/src/main/java/okio/RealBufferedSink.java
- okio/src/main/java/okio/RealBufferedSource.java
This removes 5 methods taking the count to 607 from 612.
> Remove synthetic accessors for private members in different scopes.

- okio/src/main/java/okio/ByteString.java
- okio/src/main/java/okio/SegmentedByteString.java
- okio/src/test/java/okio/ByteStringTest.java
This avoids an unnecessary copy.
> Added ByteString.asByteBuffer().

- okio/src/main/java/okio/SegmentedByteString.java
- okio/src/test/java/okio/BufferTest.java
> Limit snapshot byte strings to requested size.

- okio/src/main/java/okio/AsyncTimeout.java
- okio/src/test/java/okio/AsyncTimeoutTest.java
- okio/src/test/java/okio/BufferTest.java
- okio/src/test/java/okio/TestUtil.java
Previously large writes could easly suffer timeouts because the entire
write was subject to a single timeout.
With this change we split the write up into 64 KiB chunks and each
chunk gets its own timeout window. This way the timeout is more granular:
it triggers if the write fails to make forward progress, not if the
entire write fails to complete within its window.
See https://github.com/square/okhttp/issues/2122
> Change write timeouts to have a maximum write size.

- okio/src/main/java/okio/Buffer.java
- okio/src/main/java/okio/ByteString.java
- okio/src/main/java/okio/HashingSink.java
- okio/src/main/java/okio/HashingSource.java
- okio/src/test/java/okio/ByteStringTest.java
- okio/src/test/java/okio/HashingSinkTest.java
- okio/src/test/java/okio/HashingSourceTest.java
- okio/src/test/java/okio/HashingTest.java
Make it a little more extravagant.
Closes https://github.com/square/okio/issues/195
> Add md5(), sha1(), and sha256() methods to Buffer.

- CHANGELOG.md
@swankjesse forgot in his commit 0b3635a34b2e2f02572f62bb989ec8ac053dcf99 that this year marks the **2016** anniversary of jesus christ death.
This PR changes the changelog date for version `1.7.0` from _2015-04-10_ to _2016-04-10_
> fix wrong changelog date for Version 1.7.0

- okio/src/main/java/okio/Buffer.java
- okio/src/main/java/okio/BufferedSource.java
- okio/src/main/java/okio/RealBufferedSource.java
- okio/src/test/java/okio/BufferedSourceTest.java
I spent a lot of time working on an alternate version that took a
Selection object. It modeled a 'compiled' variant of the List<String>
that had certain optimizations applied. Unfortunately the benefits
of these optimizations weren't worth the complexity: they improved
performance only when the choices were very long strings.
This API is not particularly extensible. If we ever found optimizations
that require the bytestrings to be sorted, or converted into a trie,
or something else, this API prevents that. From my investigation this
is a reasonable tradeoff; those approaches have been explored and aren't
that compelling!
> Implement BufferedSource.select(List<ByteString>).

- okio/src/main/java/okio/Buffer.java
- okio/src/main/java/okio/BufferedSource.java
- okio/src/main/java/okio/ByteString.java
- okio/src/main/java/okio/Options.java
- okio/src/main/java/okio/RealBufferedSource.java
- okio/src/main/java/okio/SegmentedByteString.java
- okio/src/test/java/okio/BufferedSourceTest.java
This gives us flexibility going forward in case we decide to more
strict validation on options (no empty options?) or if we want to
precompute a trie or similar.
> Change BufferedSource.select to take an Options type.

- okio/src/main/java/okio/Buffer.java
- okio/src/main/java/okio/ByteString.java
- okio/src/main/java/okio/RealBufferedSource.java
- okio/src/test/java/okio/BufferTest.java
- okio/src/test/java/okio/BufferedSinkTest.java
- okio/src/test/java/okio/ByteStringTest.java
- okio/src/test/java/okio/ReadUtf8LineTest.java
- okio/src/test/java/okio/RealBufferedSinkTest.java
If the data looks like text, this returns text. Otherwise it returns hex.
MD5 checksums are no longer used.
> Friendlier toString for ByteStrings and Buffers.

- okio/src/main/java/okio/HashingSource.java
- okio/src/test/java/okio/HashingSinkTest.java
- okio/src/test/java/okio/HashingSourceTest.java
- okio/src/test/java/okio/HashingTest.java
There was a bug where it wasn't traversing through the segments of
the buffer being hashed. This means that HashingSource was returning
incorrect answers for any writes that spanned multiple segment
boundaries.
The problem wasn't detected by our test cases because although
we have tests for non-uniform segments, and for buffers that
span multiple segments, we don't have tests for non-uniform
buffers that span multiple segments. This has been fixed too.
> Fix a major bug where HashingSource is incorrect for large writes.

- okio/src/main/java/okio/Buffer.java
- okio/src/main/java/okio/RealBufferedSource.java
- okio/src/test/java/okio/BufferedSourceTest.java
This matches String.regionMatches and ByteString.rangeEquals behavior.
> Be forgiving in rangeEquals arguments.

- okio/src/main/java/okio/Okio.java
- okio/src/test/java/okio/OkioTest.java
This adds `Okio.blackhole()` which returns a Sink that writes to the void.
Fixes #229
> Add blackhole Sink.

- okio/src/test/java/okio/PipeTest.java
- okio/src/test/java/okio/WaitUntilNotifiedTest.java
Use the JUnit 4 version in the couple of places were JUnit 3 imports
still existed; this makes the imports more consistent and also fixes
compilation if the JUnit 3 version is not available.
> Import org.junit.Assert.fail instead of junit.framework.TestCase.fail

- okio/src/main/java/okio/Base64.java
The order of operations matters. Do the division first to ensure we always arrive at the correct multiple of 4.
> Don't overallocate when base64-encoding.

- okio/src/main/java/okio/GzipSource.java
Closes: https://github.com/square/okio/issues/250
> Fix GzipSource to handle large files on AOSP.

- okio/src/main/java/okio/GzipSink.java
Though the behavior is the same as the previous method, this seems
like a more reliable approach and less likely to break on overflow.
> Fix GzipSink for symmetry.

- okio/src/main/java/okio/AsyncTimeout.java
- okio/src/test/java/okio/AsyncTimeoutTest.java
This should make it possible for people doing class unloading to
unload class loaders containing Okio.
Closes https://github.com/square/okio/issues/107
> Exit the watchdog thread after being idle for 60 seconds.

- okio/src/main/java/okio/Buffer.java
- okio/src/test/java/okio/BufferedSinkTest.java
Closes: https://github.com/square/okio/issues/258
> Fix a major bug where writeString() didn't always respect offsets.

- okio/src/main/java/okio/ByteString.java
- okio/src/test/java/okio/ByteStringTest.java
Add support for creating ByteStrings from NIO ByteBuffers.  Useful for
projects which standardized on okio for their own code but still need to
integrate with other libraries based on NIO.
Signed-off-by: Kent R. Spillner <kspillner@acm.org>
> ByteString: support creating from NIO ByteBuffers

- okio/src/main/java/okio/Buffer.java
- okio/src/main/java/okio/ByteString.java
- okio/src/main/java/okio/HashingSink.java
- okio/src/main/java/okio/HashingSource.java
- okio/src/main/java/okio/SegmentedByteString.java
- okio/src/test/java/okio/HashingSinkTest.java
- okio/src/test/java/okio/HashingSourceTest.java
- okio/src/test/java/okio/HashingTest.java
This adds APIs to ByteString, Buffer, HashingSource and HashingSink.
I've forgone polymporphism in HashingSource and HashingSink because it
adds more code than it saves. I can be convinced here.
Closes: https://github.com/square/okio/issues/254
> Implement HMAC SHA-1 and HMAC-SHA-256 throughout Okio.

- okio/src/main/java/okio/AsyncTimeout.java
Saves 1 method. (head is accessed int the private static inner class `Watchdog`)
> Remove creation of synthetic accessor method.

- okio/src/main/java/okio/ByteString.java
Rename the parameter of `ByteString.endsWith()` from prefix to suffix
> endsWith -> suffix

- README.md
This was discussed a bit here https://github.com/square/retrofit/pull/2090
This adds the ProGuard rules for okio. The format is taken from Picasso. I also added the license footer to the README, as it seems most other Square libraries have it
> Add pro guard rules to readme

- okio/src/main/java/okio/Buffer.java
- okio/src/test/java/okio/Utf8Test.java
https://github.com/square/okhttp/pull/3189/files
> Write '?' for a partial surrogate rather than throwing.

- okio/src/main/java/okio/Pipe.java
- okio/src/test/java/okio/PipeTest.java
The current behavior blocks until a reader reads the data. This is unlikely
to be useful (there's no guarantee the consumed data is handled) and makes
certain use cases more difficult to implement.
Closes: https://github.com/square/okio/issues/272
> Change Pipe's sink.flush() to not block.

- okio/src/main/java/okio/Buffer.java
- okio/src/main/java/okio/Utf8.java
- okio/src/test/java/okio/Utf8Test.java
Closes: https://github.com/square/okio/issues/283
> New Utf8.size() method to get a string's UTF-8 length.

- okio/pom.xml
- okio/src/main/java/okio/AsyncTimeout.java
- okio/src/main/java/okio/Buffer.java
- okio/src/main/java/okio/BufferedSource.java
- okio/src/main/java/okio/ByteString.java
- okio/src/main/java/okio/HashingSink.java
- okio/src/main/java/okio/Okio.java
- okio/src/main/java/okio/RealBufferedSource.java
- okio/src/main/java/okio/Segment.java
- okio/src/main/java/okio/SegmentPool.java
- okio/src/main/java/okio/package-info.java
- pom.xml
The result is that IntelliJ + Kotlin correctly infers the right nullability
for Okio's APIs. I used IntelliJ's "Specify types explicitly" quick fix on
the 'a' and 'b' variables below and it did the right thing.
fun specifyTypeExplicitly(source: BufferedSource) {
val a: String? = source.readUtf8Line()
val b: String = source.readUtf8LineStrict()
}
> Import jsr305 and use it to mark @Nullable stuff.

- okio/src/main/java/okio/AsyncTimeout.java
Previously the behavior was correct but the intended behavior was less
efficient than intended. In particular there were two problems:
* The loop to find a segment boundary may have made more iterations
than necessary if the first segment was very small
* The sink write may not have been on a segment boundary, causing more
data than necessary to be copied.
Closes: https://github.com/square/okio/issues/311
> Fix a performance bug in AsyncTimeout.sink().write().

- checkstyle.xml
- okio/src/main/java/okio/Buffer.java
- okio/src/main/java/okio/Segment.java
- okio/src/main/java/okio/SegmentedByteString.java
- okio/src/test/java/okio/BufferCursorTest.java
- okio/src/test/java/okio/SegmentSharingTest.java
- okio/src/test/java/okio/TestUtil.java
This offers direct access to the byte arrays inside the buffer's
segments. It's very low-level and only appropriate for low-level
integration: compression frameworks, encryption libraries, etc.
Closes: https://github.com/square/okio/issues/141
> Unsafe access to segment byte arrays.

- okio/src/main/java/okio/Okio.java
- This PR is coming from an okhttp PR that attempted to fix the issue.  I was asked to make this fix here instead.  https://github.com/square/okhttp/pull/3796
- Checking if input or output streams are null and throwing IOException so that okhttp properly catches the error.  This is to avoid an uncommon crash where a Socket's in/output stream is null
```
Fatal Exception: java.lang.IllegalArgumentException: out == null
at okio.Okio.sink(SourceFile:69)
at okio.Okio.sink(SourceFile:118)
at okhttp3.internal.connection.RealConnection.connectSocket(SourceFile:251)
at okhttp3.internal.connection.RealConnection.connect(SourceFile:158)
at okhttp3.internal.connection.StreamAllocation.findConnection(SourceFile:256)
at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(SourceFile:134) …
```
> Null checking and throwing IOException

- benchmarks/src/main/java/com/squareup/okio/benchmarks/BufferCursorSeekBenchmark.java
- okio/src/main/java/okio/Buffer.java
Allow the cursor to seek either forwards or backwards, starting from either the beginning, end, or current offset depending on which location is closest to the desired offset.
> Buffer cursor seek performance

- benchmarks/src/main/java/com/squareup/okio/benchmarks/GetByteBenchmark.java
- okio/src/main/java/okio/Buffer.java
Uses of Buffer.getByte() within the Okio project access it more often relative to the end of the Buffer instead of from the beginning.  Specifically the ReadBufferedSource.readHexadecimalUnsignedLong() and ReadBufferedSource.readDecimalLong() methods make heavy use of retrieving the latest byte from the Buffer and with this change, the unit tests for these methods with the OneByteAtATime source no longer take over a second to run.
A benchmark for this behavior has been created and verified to show significant improvement.
Before:
```
Benchmark                                    (bufferSize)    Mode  Samples  Score   Error  Units
c.s.o.b.GetByteBenchmark.getByteBeginning         2097152  sample   160460  0.037 ± 0.003  us/op
c.s.o.b.GetByteBenchmark.getByteEnd               2097152  sample …
```
> Allow Buffer.getByte() to search backwards for the desired segment

- okio/pom.xml
> Add 'Automatic-Module-Name' entry to manifest

- okio/src/main/java/okio/InflaterSource.java
- okio/src/test/java/okio/InflaterSourceTest.java
Instead of reading the requested byte count, InflaterSource will read
to fill up the unused portion of the tail segment.  Correct this by
taking the minimum amount between the unused segment length and the byte
count.
Add two test cases to validate this behavior and catch any regressions.
> InflaterSource needs to honor read byte count

- okio/src/main/java/okio/Buffer.java
- okio/src/main/java/okio/BufferedSink.java
- okio/src/main/java/okio/BufferedSource.java
- okio/src/main/java/okio/RealBufferedSink.java
- okio/src/main/java/okio/RealBufferedSource.java
- okio/src/test/java/okio/BufferedSinkTest.java
- okio/src/test/java/okio/BufferedSourceTest.java
- okio/src/test/java/okio/NioTest.java
I was looking at hooking up Okio to Brotli. Their JNI API wants us
to implement these JNI interfaces. The cost of implementing them is
pretty low, and the upside interop should be convenient.
These new APIs require bytes to be copied. This is just how the
NIO APIs work.
Closes: https://github.com/square/okio/issues/318
> Implement ReadableByteChannel and WritableByteChannel.

- okio/src/main/java/okio/Buffer.java
- okio/src/test/java/okio/BufferCursorTest.java
Both seek to the end of the original buffer if it is being enlarged. Otherwise
to the end of the new smaller buffer.
> Change resizeBuffer() and expandBuffer() to seek.

- samples/src/main/java/okio/samples/Interceptors.java
Create a sample which demonstrates a basic use for Buffer.UnsafeCursor.
This shows an InterceptingSource and InterceptingSink which both allow
raw access to the bytes being read and written before they are
propagated. These are used to demo a circular cipher.
Fixes: #330
> Sample to show intercepting of source/sink Buffer via UnsafeCursor

- okio/src/main/java/okio/Sink.java
- okio/src/main/java/okio/Source.java
`Sink` and `Source` are not really classes. They're interfaces. In general I think it makes more sense to communicate that this library uses BufferedSink/Source to achieve the equivalent of the Java APIs.
In case you don't agree with it feel free to close.
> Documentation improvement for Sink and Source.

- build.gradle
- okio/build.gradle
When I renamed `Okio.sink(Socket)` to `Okio.kitchenSink(Socket)`:
```
$ gw :okio:check
> Task :okio:japicmp FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':okio:japicmp'.
> A failure occurred while executing Comparing [okio-1.15.0-SNAPSHOT.jar] with [okio-1.14.0.jar]
> Detected binary changes between okio-1.15.0-SNAPSHOT.jar and okio-1.14.0.jar. See failure report at file:///Users/jakew/dev/square/okio/okio/build/reports/japi.txt
$ cat okio/build/reports/japi.txt
Comparing binary compatibility of  against
***! MODIFIED CLASS: PUBLIC FINAL okio.Okio  (not serializable)
---! REMOVED METHOD: PUBLIC(-) STATIC(-) okio.Sink sink(java.net.Socket)
---  REMOVED EXCEPTION: java.io.IOException
```
> Add JApicmp to validate public API compatibility.

- .travis.yml
Closes #392 
This will `cat` even if the failure wasn't caused by Japicmp, maybe there's a cleaner solution
> Print JApicmp output on build failure

- checkstyle.xml
- okio/src/main/java/okio/Buffer.java
- okio/src/main/java/okio/GzipSink.java
- okio/src/main/java/okio/HashingSink.java
- okio/src/main/java/okio/HashingSource.java
- okio/src/main/java/okio/InflaterSource.java
- okio/src/main/java/okio/Options.java
- okio/src/main/java/okio/Pipe.java
- okio/src/main/java/okio/Segment.java
This will make it easier for 2.x to be compatible according to japicmp.
> Explicitly declare some members as final in Okio 1.x.

- okio/jvm/src/test/java/okio/BufferedSourceTest.java
There was a performance bug here, where it would return one segment too early.
> Add a test for the off-by-one bug in Buffer.seek().

- okio/jvm/src/main/java/okio/Buffer.kt
- okio/jvm/src/test/java/okio/TestUtil.kt
With the new Buffer.UnsafeCursor API, this method can be replaced by
navigating the Buffer with a cursor. This removes a method that is only
used in the test package and was marked as for testing only.
> Remove test-only method `segmentSizes` from Buffer

- okio/jvm/src/main/java/okio/Buffer.kt
- okio/jvm/src/test/java/okio/OptionsTest.kt
This found one condition that wasn't covered by the existing tests. I also wrote
targeted whitebox tests for each of the interesting cases in the code. Tests are
cheap and confidence is valuable.
One other thing this brought up is that we don't support empty byte strings any
more, which simplifies one case.
> Do coverage-driven testing of Buffer.select().

- samples/src/main/java/okio/samples/ByteChannelSink.java
- samples/src/main/java/okio/samples/ByteChannelSource.java
- samples/src/main/java/okio/samples/FileChannelSink.java
- samples/src/main/java/okio/samples/FileChannelSource.java
- samples/src/main/java/okio/samples/Interceptors.java
- samples/src/test/java/okio/samples/ChannelsTest.java
First part of the samples shows how to create a Source or Sink from a
ReadableByteChannel or a WritableByteChannel respectively. This uses the
UnsafeCursor to give the NIO channel direct access to the bytes within
the Buffer by wrapping the internal segments with a ByteBuffer.
The second part shows how to take advantage of the FileChannel's
transferFrom and transferTo methods. Again, this allows direct access to
the data being read or written, but this time by giving the Buffer the
ByteBuffers used by the FileChannel.
> Samples which show integration with Java NIO channels

- okio/jvm/src/main/java/okio/AsyncTimeout.kt
- okio/jvm/src/main/java/okio/BufferedSink.kt
- okio/jvm/src/main/java/okio/BufferedSource.kt
- okio/jvm/src/main/java/okio/ByteString.kt
- okio/jvm/src/main/java/okio/ForwardingSink.kt
- okio/jvm/src/main/java/okio/ForwardingSource.kt
- okio/jvm/src/main/java/okio/GzipSink.kt
- okio/jvm/src/main/java/okio/GzipSource.kt
- okio/jvm/src/main/java/okio/HashingSink.kt
- okio/jvm/src/main/java/okio/HashingSource.kt
- okio/jvm/src/main/java/okio/InflaterSource.kt
- okio/jvm/src/main/java/okio/Okio.kt
- okio/jvm/src/main/java/okio/RealBufferedSink.kt
- okio/jvm/src/main/java/okio/RealBufferedSource.kt
- okio/jvm/src/main/java/okio/Sink.kt
- okio/jvm/src/main/java/okio/Source.kt
- okio/jvm/src/main/java/okio/Timeout.kt
- okio/jvm/src/main/java/okio/package-info.java
This changes Okio to stop catching impossible exceptions, such as when an
algorithm is required by the VM but not present at runtime.
Also don't declare exceptions in internal classes.
> Fix some formatting and style problems.

- okio/js/src/main/kotlin/okio/ByteString.kt
- okio/jvm/src/main/java/okio/ByteString.kt
- okio/jvm/src/main/java/okio/SegmentedByteString.kt
- okio/jvm/src/test/java/okio/ByteStringKotlinTest.kt
- okio/src/main/kotlin/okio/ByteString.kt
This moves it out of common because default parameters and expect/actual don't
interact well.
> Add default parametes to ByteString.substring

- okio/jvm/src/main/java/okio/Timeout.kt
- okio/jvm/src/test/java/okio/WaitUntilNotifiedTest.java
This fixes Okio 2.x. A separate fix is required for Okio 1.x.
> Retain interrupted state when throwing InterruptedIOException (Okio 2.x)

- okio/src/main/java/okio/Timeout.java
- okio/src/test/java/okio/WaitUntilNotifiedTest.java
This fixes Okio 1.x. A separate fix is required for Okio 2.x.
> Retain interrupted state when throwing InterruptedIOException

- okio/js/src/main/kotlin/okio/ByteString.kt
- okio/jvm/src/main/java/okio/Buffer.kt
- okio/jvm/src/main/java/okio/ByteString.kt
- okio/jvm/src/main/java/okio/HashingSink.kt
- okio/jvm/src/main/java/okio/HashingSource.kt
- okio/jvm/src/test/java/okio/ByteStringTest.java
- okio/jvm/src/test/java/okio/HashingSinkTest.java
- okio/jvm/src/test/java/okio/HashingSourceTest.java
- okio/src/main/kotlin/okio/common/ByteString.kt
ByteString.of() was copying the data 2 extra times before passing it to
the commonOf() method. Avoid these extra copies by converting the
commonOf() method to take a ByteArray directly and only copy the array
in that method.
MessageDigests and Macs create unique ByteArrays which can safely be
wrapped directly with a ByteString without having to copy the array.
Avoid the spread operator and using the ByteString.of() create method.
> Avoid excess ByteArray copies when creating ByteStrings

- okio/src/main/java/okio/Options.java
I decided it was counterproductive to support an empty string option
> Remove some unreachable code building the Options trie

- okio/jvm/src/main/java/okio/Options.kt
I decided it was counterproductive to support an empty string option
> Remove some unreachable code building the Options trie (Okio 2x)

- okio/src/main/java/okio/Options.java
- okio/src/test/java/okio/BufferedSourceTest.java
- okio/src/test/java/okio/OptionsTest.java
Moshi relies on this and it's convenient to avoid a special case in
calling code.
> Restore support for the empty set of options.

- okio/jvm/src/main/java/okio/Options.kt
- okio/jvm/src/test/java/okio/BufferedSourceTest.java
- okio/jvm/src/test/java/okio/OptionsTest.kt
Moshi relies on this and it's convenient to avoid a special case in
calling code.
> Restore support for the empty set of options. (Okio 2x)

- okio/jvm/src/main/java/okio/Buffer.kt
- okio/jvm/src/test/java/okio/TestUtil.kt
- okio/src/main/kotlin/okio/Segment.kt
Segment doesn't override equals() so reference equality is preferred.
> Don't use equals() on Segments

- build.gradle
- okio/js/src/main/kotlin/okio/-Platform.kt
- okio/js/src/main/kotlin/okio/ByteString.kt
- okio/jvm/build.gradle
- okio/jvm/src/jmh/java/com/squareup/okio/benchmarks/BenchmarkUtils.kt
- okio/jvm/src/jmh/java/com/squareup/okio/benchmarks/BufferUtf8Benchmark.java
- okio/jvm/src/jmh/java/com/squareup/okio/benchmarks/Utf8Benchmark.java
- okio/jvm/src/main/java/okio/-Platform.kt
- okio/jvm/src/main/java/okio/Buffer.kt
- okio/jvm/src/main/java/okio/ByteString.kt
- okio/jvm/src/test/java/okio/ByteStringKotlinTest.kt
- okio/jvm/src/test/java/okio/TestUtil.kt
- okio/jvm/src/test/java/okio/Utf8Test.java
- okio/native/src/main/kotlin/okio/-Platform.kt
- okio/native/src/main/kotlin/okio/ByteString.kt
- okio/src/main/kotlin/okio/-Platform.kt
- okio/src/main/kotlin/okio/-Util.kt
- okio/src/main/kotlin/okio/ByteString.kt
- okio/src/main/kotlin/okio/Utf8.kt
- okio/src/main/kotlin/okio/internal/-Utf8.kt
- okio/src/main/kotlin/okio/internal/ByteString.kt
- okio/src/test/kotlin/okio/ByteStringTest.kt
- okio/src/test/kotlin/okio/Utf8KotlinTest.kt
Kotlin/JS does not currently have a implementation for transforming a
UTF-8 encoded ByteArray into a String and vice versa. Create an
implementation using some of the logic which already exists within Okio.
While this implementation could be used for Kotlin/JVM and
Kotlin/Native, both of these platforms have their own implementation
which is faster.
Fixes #452
Since I was already working in this area because of #469, I made an attempt to implement UTF-8 encoding and decoding for Kotlin/JS. I decided on implementing this in Kotlin because there might be other places throughout the project we might want to use these inline functions.
For contrast, [kotlinx-io](https://github.com/Kotlin/kotlinx-io/) uses the `text-encoding` JS library. I would submit that implementing native in Okio keeps …
> Implement UTF-8 encode and decode for JS

- okio/jvm/src/main/java/okio/AsyncTimeout.kt
- okio/jvm/src/test/java/okio/AsyncTimeoutTest.java
The wrapping Source for an AsyncTimeout was missing a call to enter() in
close(). This means a timeout would never occur if closing the Source
took longer than then the current timeout.
Added some unit tests to cover this case as well for both Source and
Sink and close() and flush().
> AsyncTimeout wrapped Source needs to timeout on long close

- okio/js/src/main/kotlin/okio/ByteString.kt
- okio/jvm/src/jmh/java/com/squareup/okio/benchmarks/SegmentedByteStringBenchmark.java
- okio/jvm/src/main/java/okio/Buffer.kt
- okio/jvm/src/main/java/okio/ByteString.kt
- okio/jvm/src/main/java/okio/SegmentedByteString.kt
- okio/native/src/main/kotlin/okio/ByteString.kt
- okio/src/main/kotlin/okio/internal/ByteString.kt
Inspired after #514, I started taking a look at creating a substring for SegmentedByteString that shared segments and didn't convert to a normal first ByteString. This lead me down a road of a bunch of different optimizations that could be made to SegmentedByteString to simplify and reduce the amount of converting to a single ByteArray.
I've included each improvement as a separate commit to hopefully make reviewing it in isolation easier. I also did this in case you didn't want to include any of them, it should be pretty easy to just rebase out the commit.
> Various SegmentedByteString improvements

- okio/jvm/src/main/java/okio/Throttler.kt
- okio/jvm/src/test/java/okio/Stopwatch.kt
- okio/jvm/src/test/java/okio/ThrottlerTest.kt
Closes #490 
Created a sample Throttler which can throttle Sources and Sinks to a
desired throughput. Multiple Sources and Sinks can be attached to the
same Throttler and their combined throughput will not exceed the desired
throughput. Multiple Throttlers can also be used on the same Source or
Sink and they will all be honored.
Added some basic unit tests to verify desired behavior.
> Create a Throttler sample

- okio/jvm/src/main/java/okio/Throttler.kt
- okio/jvm/src/test/java/okio/ThrottlerTakeTest.kt
This requires a few small refactorings to Throttler. But not much.
The new test is 100% deterministic. It means we can write a lot
better tests for edge cases around truncating division, etc.
> New test for Throttler that isn't racy.

- okio/jvm/src/main/java/okio/Throttler.kt
- okio/jvm/src/test/java/okio/ThrottlerTakeTest.kt
- okio/jvm/src/test/java/okio/ThrottlerTest.kt
That causes an infinite wait, which we never want
> Don't wait 0 nanoseconds

- okio/build.gradle
> Use api instead of implementation for the kotlin-stdlib dependency

- okio/build.gradle
Instead of _adding_ desired source directories, _replace_ the existing,
default source directories with the custom layout used by Okio. This
makes IntelliJ *much* happier about the project layout.
closes #580 - I was finally able to figure this out without having to move any files. `samples` is still causing problems but I'll keep working on it.
> Replace default Gradle source directories with custom layout

- build.gradle
- okio/jvm/japicmp/build.gradle
This bumps japicmp to 0.13.1 which still doesn't contain the effectively-final fix, but at least provides compatibility with newer japicmp versions so that we can upgrade once that change is released.
> Update japicmp plugin

- okio/jvm/src/test/java/okio/BufferedSourceTest.java
- okio/src/main/kotlin/okio/PeekSource.kt
The contract for read() is to return at least 1 byte, but we were
attempting to read the full request. That caused us to prematurely
do a blocking read on the upstream source.
This fixes that code to defer the blocking read.
Closes: https://github.com/square/okio/issues/594
> Peek the minimum number of bytes to return a result

- .travis.yml
- gradle/gradle-mvn-mpp-push.gradle
Still figuring this out:
- ~Publishing doesn't seem to work without enabling `GRADLE_METADATA`, do we really need it?~
- ~Right now the JVM artifact gets published under the `okio` ID, which as I understand in multiplatform world get taken by the metadata artifact. I've also seen that SQLDelight's metadata is under `runtime-metadata`. Is there special config needed to get `okio-metadata` to contain metadata, and `okio` to contain the JVM artifact?~
> Configure Travis to run builds on OSX and publish artifacts for all platforms

- gradle/gradle-mvn-mpp-push.gradle
With current setup JVM artifact gets published on top of the common one, which makes it impossible to consume the library from a multiplatform project. Removing artifact name override for the JVM module will change it to `okio-jvm`, which will break existing library users (more precisely, existing users that don't use Gradle, whoever is consuming Okio through Gradle is fine thanks to metadata). I suggest overriding the common artifact name to `okio-multiplatform`, probably until 3.0.
> Rename common artifact to 'okio-multiplatform' to avoid name clash

- okio/src/commonMain/kotlin/okio/-Util.kt
- okio/src/commonMain/kotlin/okio/Buffer.kt
- okio/src/commonMain/kotlin/okio/BufferedSource.kt
- okio/src/commonMain/kotlin/okio/SegmentPool.kt
- okio/src/commonMain/kotlin/okio/internal/-Utf8.kt
- okio/src/commonMain/kotlin/okio/internal/Buffer.kt
- okio/src/commonMain/kotlin/okio/internal/ByteString.kt
- okio/src/commonTest/kotlin/okio/CommonBufferTest.kt
- okio/src/commonTest/kotlin/okio/CommonOptionsTest.kt
- okio/src/commonTest/kotlin/okio/MockSink.kt
- okio/src/commonTest/kotlin/okio/util.kt
- okio/src/jsMain/kotlin/okio/Buffer.kt
- okio/src/jsMain/kotlin/okio/BufferedSource.kt
- okio/src/jvmMain/kotlin/okio/Buffer.kt
- okio/src/jvmMain/kotlin/okio/BufferedSource.kt
- okio/src/jvmMain/kotlin/okio/RealBufferedSource.kt
- okio/src/nativeMain/kotlin/okio/Buffer.kt
- okio/src/nativeMain/kotlin/okio/BufferedSource.kt
Cut-pasted all the Buffer methods which don't rely on Java specifics to Kotlin/Common. Also copied the buffer unit tests but left the existing tests as is. Want to make sure we maintain that coverage during this transition.
I'll go through and point out anything I did which might be questionable.
> Add Buffer implementation to Kotlin/JS and Kotlin/Native

- build.gradle
Wire would benefit from an Okio snapshot built against this version, so as long as there are no Okio releases planned in the immediate future, I'd love to merge this.
> Kotlin 1.3.50-eap

- build.gradle
- okio/src/jvmTest/kotlin/okio/BufferCursorKotlinTest.kt
- okio/src/jvmTest/kotlin/okio/TestUtil.kt
Replace `Array.fill` usage with new `Array.fill` extension from stdlib.
> Kotlin 1.3.50

- docs/releasing.md
This avoids putting credentials on the file system.
> Borrow OkHttp's releasing doc

- okio/src/commonMain/kotlin/okio/-Util.kt
- okio/src/commonMain/kotlin/okio/Buffer.kt
- okio/src/commonMain/kotlin/okio/Okio.kt
- okio/src/commonMain/kotlin/okio/RealBufferedSink.kt
- okio/src/commonMain/kotlin/okio/RealBufferedSource.kt
- okio/src/commonMain/kotlin/okio/internal/Buffer.kt
- okio/src/commonMain/kotlin/okio/internal/RealBufferedSink.kt
- okio/src/commonMain/kotlin/okio/internal/RealBufferedSource.kt
- okio/src/commonTest/kotlin/okio/BufferedSinkFactory.kt
- okio/src/commonTest/kotlin/okio/BufferedSinkTest.kt
- okio/src/commonTest/kotlin/okio/BufferedSourceFactory.kt
- okio/src/commonTest/kotlin/okio/BufferedSourceTest.kt
- okio/src/commonTest/kotlin/okio/ByteStringFactory.kt
- okio/src/commonTest/kotlin/okio/ByteStringTest.kt
- okio/src/commonTest/kotlin/okio/CommonOkioKotlinTest.kt
- okio/src/commonTest/kotlin/okio/CommonRealBufferedSinkTest.kt
- okio/src/commonTest/kotlin/okio/CommonRealBufferedSourceTest.kt
- okio/src/commonTest/kotlin/okio/util.kt
- okio/src/jsMain/kotlin/okio/Buffer.kt
- okio/src/jsMain/kotlin/okio/RealBufferedSink.kt
- okio/src/jsMain/kotlin/okio/RealBufferedSource.kt
- okio/src/jvmMain/kotlin/okio/Buffer.kt
- okio/src/jvmMain/kotlin/okio/Okio.kt
- okio/src/jvmTest/kotlin/okio/OkioKotlinTest.kt
- okio/src/nativeMain/kotlin/okio/Buffer.kt
- okio/src/nativeMain/kotlin/okio/Okio.kt
- okio/src/nativeMain/kotlin/okio/RealBufferedSink.kt
- okio/src/nativeMain/kotlin/okio/RealBufferedSource.kt
Copied the BufferedSourceTest and BufferedSinkTest files to Kotlin/Common. This involved converting them to Kotlin (thanks IntelliJ), changing parameterized unit test mechanism, removing Java specific unit tests, adding the `Buffer#copy()` method as an alternative to Java specific `Buffer#clone()`, and fixing a bug.
I've also moved RealBufferedSource and RealBufferedSink to Kotlin/Common but wanted to start this pull request with the unit test move.
> Copy RealBufferedSink and RealBufferedSource to Kotlin/Common

- okio/src/jvmMain/kotlin/okio/AsyncTimeout.kt
Follow up to #661 
It is possible to make internal functions available to an inline'd function using the `@PublishedApi` annotation. This effectively makes them part of the public API of the project but only usable through the the inline function.
We could take this one step farther and remove the 2 internal `exit` functions since they are only used from the `withTimeout` function. However, this would mean making `newTimeoutException` public as well.
> Make AsyncTimeout.withTimeout public

- okio/src/main/java/okio/Buffer.java
- okio/src/main/java/okio/Okio.java
- okio/src/test/java/okio/BufferTest.java
- okio/src/test/java/okio/OkioTest.java
- okio/src/test/java/okio/TestUtil.java
Manual backport of cketti's change
https://github.com/square/okio/pull/686/commits
> Remove empty tail segment (1.x branch)

- okio/jvm/jmh/src/jmh/java/com/squareup/okio/benchmarks/ReadByteStringBenchmark.java
- okio/src/commonMain/kotlin/okio/internal/Buffer.kt
- okio/src/commonTest/kotlin/okio/CommonBufferTest.kt
- okio/src/jvmTest/java/okio/BufferTest.java
> Use SegmentedByteString when reading a significantly large ByteString

- .travis.yml
This is instead of using oraclejdk8
The Oracle Jdk8 doesn't seem to be supported by Travis on Xenial:
https://travis-ci.community/t/expected-feature-release-number-in-range-of-9-to-12-but-got-8-installing-oraclejdk8/1345/8
> Switch travis to use openjdk8

- okio/jvm/jmh/build.gradle
These old platform plugins are going away in 1.4
> Use regular JVM plugin for JMH

- okio/src/commonTest/kotlin/okio/BufferedSourceFactory.kt
- okio/src/jvmMain/kotlin/okio/InflaterSource.kt
- okio/src/jvmTest/java/okio/InflaterSourceTest.java
This is similar to read() but it may return 0 bytes.
Also rework InflaterSourceTest to exercise code paths where different
numbers of bytes are ready on each round.
> New API, InflaterSource.readOrInflate

- okio/src/jsMain/kotlin/okio/SegmentPool.kt
- okio/src/jvmMain/kotlin/okio/SegmentPool.kt
- okio/src/jvmTest/kotlin/okio/SegmentSharingTest.kt
- okio/src/jvmTest/kotlin/okio/TestUtil.kt
- okio/src/nativeMain/kotlin/okio/SegmentPool.kt
Under a high contention environment we'll do more zero-fill and GC
instead of locking.
> Make the segment pool lock-free on the JVM

- okio/src/jvmMain/kotlin/okio/Pipe.kt
- okio/src/jvmTest/kotlin/okio/PipeKotlinTest.kt
I wanted this when attempting to implement java.io.Socket on top of a
pair of Pipe instances.
> New API: Pipe.cancel()

- okio/src/commonMain/kotlin/okio/Segment.kt
- okio/src/commonMain/kotlin/okio/SegmentPool.kt
- okio/src/commonTest/kotlin/okio/CommonBufferTest.kt
- okio/src/jsMain/kotlin/okio/SegmentPool.kt
- okio/src/jvmMain/kotlin/okio/SegmentPool.kt
- okio/src/nativeMain/kotlin/okio/SegmentPool.kt
This adds a commit to @rewlad's [PR 725](https://github.com/square/okio/pull/725).
> Use multiple linked lists to reduce contention in the segment pool

- okio/src/jvmMain/kotlin/okio/JvmOkio.kt
This is surprisingly expensive.
> Don't recompute the logger for every SocketAsyncTimeout

- okio/jvm/jmh/src/jmh/java/com/squareup/okio/benchmarks/MessageDigestBenchmark.java
- okio/src/commonMain/kotlin/okio/internal/AbstractMessageDigest.kt
- okio/src/commonMain/kotlin/okio/internal/HashUtil.kt
- okio/src/commonMain/kotlin/okio/internal/MD5MessageDigest.kt
- okio/src/commonMain/kotlin/okio/internal/OkioMessageDigest.kt
- okio/src/commonMain/kotlin/okio/internal/Sha1MessageDigest.kt
- okio/src/commonMain/kotlin/okio/internal/Sha256MessageDigest.kt
- okio/src/commonMain/kotlin/okio/internal/Sha512MessageDigest.kt
- okio/src/commonTest/kotlin/okio/OkioMessageDigestTest.kt
```
Benchmark                    (algorithm)  (messageSize)  Mode  Cnt     Score     Error  Units
MessageDigestBenchmark.jvm         SHA-1            100  avgt    3     0.408 ±   0.152  us/op
MessageDigestBenchmark.jvm         SHA-1        1048576  avgt    3  2867.138 ± 326.541  us/op
MessageDigestBenchmark.okio        SHA-1            100  avgt    3     0.546 ±   0.029  us/op
MessageDigestBenchmark.okio        SHA-1        1048576  avgt    3  2968.167 ± 430.262  us/op
```
> Optimize SHA-1.

- okio/src/commonMain/kotlin/okio/internal/Sha256MessageDigest.kt
Performance is still quite a ways off OpenJDK.
```
Benchmark                    (algorithm)  (messageSize)  Mode  Cnt     Score     Error  Units
MessageDigestBenchmark.jvm       SHA-256            100  avgt    3     0.364 ±   0.085  us/op
MessageDigestBenchmark.jvm       SHA-256        1048576  avgt    3  2620.091 ± 645.504  us/op
MessageDigestBenchmark.okio      SHA-256            100  avgt    3     0.793 ±   0.137  us/op
MessageDigestBenchmark.okio      SHA-256        1048576  avgt    3  4468.063 ± 327.770  us/op
```
> Take the allocations out of our SHA-256 implementation

- okio/src/commonMain/kotlin/okio/internal/MD5MessageDigest.kt
```
Benchmark                    (algorithm)  (messageSize)  Mode  Cnt     Score     Error  Units
MessageDigestBenchmark.jvm           MD5            100  avgt    3     0.319 ±   0.015  us/op
MessageDigestBenchmark.jvm           MD5        1048576  avgt    3  2183.831 ± 368.649  us/op
MessageDigestBenchmark.okio          MD5            100  avgt    3     0.522 ±   0.098  us/op
MessageDigestBenchmark.okio          MD5        1048576  avgt    3  3073.967 ± 204.729  us/op
```
> Optimize MD5

- build.gradle
- okio/jvm/jvm.gradle
Implementation of the build discussed in the issue #776
Fixes #776
> Added OSGi metadata via build in a non intrusive way

- okio/src/commonMain/kotlin/okio/internal/SegmentedByteString.kt
- okio/src/commonTest/kotlin/okio/BufferedSinkTest.kt
- okio/src/jvmTest/java/okio/BufferedSinkTest.java
Only occurs when performing a partial write of a SegmentedByteString into a Buffer. Partial write of a ByteString was added in 2.4.1 by #651 (yep, my bad 😬 ).
> Fix SegmentedByteString substring write

- README.md
- okio/src/jvmMain/kotlin/okio/CipherSink.kt
- okio/src/jvmMain/kotlin/okio/CipherSource.kt
- okio/src/jvmTest/kotlin/okio/CipherFactory.kt
- okio/src/jvmTest/kotlin/okio/CipherSinkTest.kt
- okio/src/jvmTest/kotlin/okio/CipherSourceTest.kt
I know #260 was closed, but I don't really understand the issue, given that the initialization of the cipher is outside of the responsibility of the stream implementation. Let me know if I this is a fool's errand, but I figure this was at least worth a shot. This would be very useful for applications which treat large amounts of ciphered data, because the usage of internal segments would be a big improvement for memory usage, not to mention the simple fact of having cryptography properly included in the okio ecosystem for piping.
> CipherSink & CipherSource

- README.md
- okio/src/jvmMain/kotlin/okio/CipherSink.kt
- okio/src/jvmMain/kotlin/okio/CipherSource.kt
- okio/src/jvmMain/kotlin/okio/JvmOkio.kt
- okio/src/jvmTest/kotlin/okio/CipherAlgorithm.kt
- okio/src/jvmTest/kotlin/okio/CipherFactory.kt
- okio/src/jvmTest/kotlin/okio/CipherSinkTest.kt
- okio/src/jvmTest/kotlin/okio/CipherSourceTest.kt
This is a hedge against needing to add new public APIs on these
types. We needed it for InflaterSource so we could have a method
that would consume bytes without necessarily returning any.
> Make CipherSink and CipherSource into public types

- okio-files/README.md
- okio-files/build.gradle
- okio-files/gradle.properties
- okio-files/src/commonMain/kotlin/okio/Filesystem.kt
- okio-files/src/commonMain/kotlin/okio/Path.kt
- okio-files/src/commonTest/kotlin/okio/files/PathTest.kt
- settings.gradle
This is a bit more experimental than I would have preferred.
Like Java's File and Path types, this uses a single type to
represent either a relative or absolute path. It attempts to
simplify '..' and '.' operators and remove unnecessary empty
paths.
> Path API for multiplatform

- okio/src/jvmMain/kotlin/okio/Timeout.kt
[fixed Issue#789](https://github.com/square/okio/issues/789)
> fix okio.Timeout#throwIfReached() thread's interrupted status check

- okio/src/jvmMain/kotlin/okio/HashingSink.kt
- okio/src/jvmMain/kotlin/okio/HashingSource.kt
- okio/src/jvmMain/kotlin/okio/JvmOkio.kt
Hello 👋 me again with more crypto stuff 😅
This MR adds similar extensions to `cipherSource` and `cipherSink` for the hashing source and sink. 
More importantly though, it exposes the `Mac` and `MessageDigest` classes directly to be able to create the hashing source or sink directly with a pre-initialized instance, rather than using one of the predefined ones. This allows more extensibility to use with other algorithms that the platform may support, but it's also more flexible to perform operations on the mac or digest instances themselves. In a way, it's also consistent with the new API for using cipher source and sink. 
My use-case is a cipher spec where the `Mac` instance needs to be initialized with a an initialization vector, before being computed for all the data. This isn't possible …
> Extensions for hashing source & sink

- okio-files/build.gradle
- okio-files/src/commonMain/kotlin/okio/Filesystem.kt
- okio-files/src/commonMain/kotlin/okio/Path.kt
- okio-files/src/commonTest/kotlin/okio/files/FileSystemTest.kt
- okio-files/src/jvmMain/kotlin/okio/JvmSystemFilesystem.kt
- okio-files/src/macosX64Main/kotlin/okio/Platform.kt
- okio-files/src/macosX64Main/kotlin/okio/PosixSystemFilesystem.kt
- okio-files/src/macosX64Main/kotlin/okio/cinterop.kt
I'm working in IntelliJ and it's been happier to track a single
target platform than several. I'll expand this to Linux and iOS
in a follow-up PR.
This satisfies egorand's recommendation of making cwd() a function
rather than a val. Annoyingly the native implementation can fail
in ways far more plausible than the JVM implementation.
> Initial native implementation of Filesystem

- okio-files/src/commonMain/kotlin/okio/Filesystem.kt
- okio-files/src/commonMain/kotlin/okio/Path.kt
- okio-files/src/commonTest/kotlin/okio/files/FileSystemTest.kt
- okio-files/src/jvmMain/kotlin/okio/Jvm.kt
- okio-files/src/jvmMain/kotlin/okio/JvmSystemFilesystem.kt
- okio-files/src/jvmTest/kotlin/okio/files/JvmSystemFilesystemTest.kt
- okio-files/src/macosX64Main/kotlin/okio/PosixSystemFilesystem.kt
I didn't implement the full move operation that works across filesystems.
That would be some straightforward code to copy a source file to a target
file using our existing source() and sink() abstractions. But it would also
require some not-straightforward code to copy other metadata such as file
permissions, created and modified dates, and extended attributes. That
method has awkward behavior in partial failures; the source file exists
and the target file does too, but possibly partially.
In real application code my preferred way of doing this would be a
copy to a temporary file on the target filesystem followed by an
atomic move of the temp file on that filesystem. This way if the
move fails partially the target file doesn't exist. Unfortunately
that strategy isn't appropriate for Okio …
> FileSystem.atomicMove()

- okio-files/build.gradle
- okio-files/src/commonMain/kotlin/okio/Filesystem.kt
- okio-files/src/commonMain/kotlin/okio/Path.kt
- okio-files/src/commonMain/kotlin/okio/Platform.kt
- okio-files/src/commonTest/kotlin/okio/files/FileSystemTest.kt
- okio-files/src/jvmMain/kotlin/okio/Jvm.kt
- okio-files/src/jvmMain/kotlin/okio/JvmSystemFilesystem.kt
- okio-files/src/jvmMain/kotlin/okio/Platform.kt
- okio-files/src/jvmTest/kotlin/okio/files/JvmSystemFilesystemTest.kt
- okio-files/src/mingwX64Main/kotlin/okio/posixVariant.kt
- okio-files/src/posixMain/kotlin/okio/PosixSystemFilesystem.kt
- okio-files/src/posixMain/kotlin/okio/cinterop.kt
- okio-files/src/posixMain/kotlin/okio/posixVariant.kt
- okio-files/src/unixMain/kotlin/okio/posixVariant.kt
Note that tests for clobbered files don't work right.
Also replace Filesystem.baseDirectory() with canonicalize(). You can get the
base directory by canonicalizing `.`. But this function is a better fit for
Windows. On that platform there can be many working directories, one per volume.
> c:\> c:\
> c:\> cd C:\Windows
> c:\Windows> a:\
> a:\> cd DOOM
> a:\DOOM> type c:notepad.exe
... prints c:\Windows\notepad.exe
> a:\DOOM> type a:DOOM.wad
... prints a:\DOOM\DOOM.wad
With canonicalize() we can get the full path to volume-relative paths
like `c:notepad.exe`.
> Basic Filesystem support for Windows

- okio-files/src/commonMain/kotlin/okio/FakeFilesystem.kt
- okio-files/src/commonMain/kotlin/okio/Filesystem.kt
- okio-files/src/commonMain/kotlin/okio/Platform.kt
- okio-files/src/commonTest/kotlin/okio/files/SystemFilesystemTest.kt
- okio-files/src/jvmMain/kotlin/okio/JvmSystemFilesystem.kt
- okio-files/src/mingwX64Main/kotlin/okio/Platform.kt
- okio-files/src/mingwX64Main/kotlin/okio/posixVariant.kt
- okio-files/src/posixMain/kotlin/okio/PosixSystemFilesystem.kt
- okio-files/src/unixMain/kotlin/okio/Platform.kt
- okio-files/src/unixMain/kotlin/okio/posixVariant.kt
I'd considered making a TEMPORARY FileSystem rooted at this directory,
but it's annoying to interop with Java I/O or user-visible paths. This
is smaller and simpler.
> Move temporaryDirectory() out of Filesystem and into a global val

- okio/src/jvmMain/kotlin/okio/CipherSink.kt
- okio/src/jvmMain/kotlin/okio/CipherSource.kt
The Android implementation of ciphers has a weird behaviour, which I would qualify as a bug. On updates to the ciphers, it throws a `ShortBufferException` if the output array is smaller than the value that it estimates through its internal call to `getOutputSizeForUpdate`, which is itself erroneous because it returns a value which is too high. 
Here's an example illustrating the issue. The error is thrown even though the requested size isn't actually needed.
```kotlin
@Test
fun testEncrypt() {
val key = Random.nextBytes(32)
val cipher = Cipher.getInstance("AES/CBC/PKCS7Padding").apply {
init(Cipher.ENCRYPT_MODE, SecretKeySpec(key, "AES"))
}
val input = Random.nextBytes(32)
val output = ByteArray(16)
var outputOffset = 0
outputOffset += cipher.update(input, 0, 1, output, outputOffset) 
// …
```
> Fix Android cipher issue

- okio-files/src/commonMain/kotlin/okio/Filesystem.kt
- okio-files/src/commonMain/kotlin/okio/Path.kt
- okio-files/src/commonTest/kotlin/okio/files/PathTest.kt
The big challenge in this design is how to offer different behavior
for Windows vs. UNIX paths without a lot of baggage in the API.
Developers shouldn't have to choose a PathScheme or something!
So instead we just use the first slash character (`/` or `\`) as
a hint.
> Windows Paths

- okio-files/build.gradle
- okio-files/src/commonMain/kotlin/okio/Filesystem.kt
- okio-files/src/commonMain/kotlin/okio/common.kt
- okio-files/src/commonTest/kotlin/okio/files/FakeFilesystemTest.kt
- okio-files/src/commonTest/kotlin/okio/files/FileSystemTest.kt
- okio-files/src/commonTest/kotlin/okio/files/time.kt
- okio-files/src/jvmMain/kotlin/okio/JvmSystemFilesystem.kt
- okio-files/src/posixMain/kotlin/okio/PosixSystemFilesystem.kt
- okio-testing/README.md
- okio-testing/build.gradle
- okio-testing/gradle.properties
- okio-testing/src/commonMain/kotlin/okio/FakeFilesystem.kt
- okio-testing/src/commonMain/kotlin/okio/time.kt
- settings.gradle
I want FakeFileSystem to depend on experimental APIs in kotlinx.datetime.
And I want to fold okio-files into the main okio module, where a dependency
on kotlinx.datetime would be too much.
> Extract FakeFileSystem into a new okio-testing module

- okio-files/src/commonTest/kotlin/okio/files/AbstractFilesystemTest.kt
- okio-files/src/commonTest/kotlin/okio/files/FakeFilesystemTest.kt
- okio-files/src/commonTest/kotlin/okio/files/SystemFilesystemTest.kt
- okio-testing/src/commonMain/kotlin/okio/FakeFilesystem.kt
This moves tests from OkHttp's WindowsFileSystem, the fake that
will be obsoleted by this.
> Support Windows limitations in FakeFileSystem

- okio-files/src/commonMain/kotlin/okio/Filesystem.kt
- okio-files/src/commonTest/kotlin/okio/files/AbstractFilesystemTest.kt
- okio-files/src/mingwX64Main/kotlin/okio/posixVariant.kt
- okio-files/src/mingwX64Main/kotlin/okio/windows.kt
- okio-files/src/posixMain/kotlin/okio/PosixSystemFilesystem.kt
- okio-files/src/posixMain/kotlin/okio/posixVariant.kt
- okio-files/src/unixMain/kotlin/okio/posixVariant.kt
- okio-testing/src/commonMain/kotlin/okio/FakeFilesystem.kt
This now uses the Windows API and its corresponding error
reporting instead of the much nicer POSIX one.
> Fix atomicMove on Windows

- okio-files/src/commonMain/kotlin/okio/Path.kt
- okio-files/src/commonTest/kotlin/okio/files/FakeFilesystemTest.kt
- okio-files/src/commonTest/kotlin/okio/files/PathTest.kt
- okio-testing/src/commonMain/kotlin/okio/FakeFilesystem.kt
Also support roots like C:\ in FakeFileSystem. These roots are created
on-demand.
> Fix parent paths for Windows paths like C:\Windows

- build.gradle
- docs/css/dokka-logo.css
- gradle/gradle-mvn-mpp-push.gradle
The latest version of Dokka allows you to add custom CSS and assets to the generated html, including the wordmark that is added to he top left of every page.
This commit replaces the default Dokka wordmark with `logo-square.png` which is already present in the repo. You'll probably want to use an different image that shows up better on a light background.
> Use custom wordmark in dokkaHtml

- okio-files/build.gradle
Add `gradle-mvn-mpp-push` to `okio-files` so the artifacts end up in snapshots.
Currently, dokka is disabled because of https://github.com/Kotlin/dokka/issues/1592
> publish okio-files

- gradle/gradle-mvn-mpp-push.gradle
Use `okio-files-multiplatform` for the okio-files multiplatform artifact so that it does not overwrite the regular `okio-multiplatform` artifact
Many thanks to @PaulWoitaschek for flagging this!
> Fix `okio-multiplatform` publication

- gradle/gradle-mvn-mpp-push.gradle
This makes the same change as #842 but for the jvm artifact instead of the multiplatform one.
> Read JVM artifact name from POM instead of hardcoding okio

- okio-testing/src/commonMain/kotlin/okio/FakeFilesystem.kt
- okio/src/commonMain/kotlin/okio/Filesystem.kt
- okio/src/commonTest/kotlin/okio/AbstractFilesystemTest.kt
- okio/src/commonTest/kotlin/okio/FakeFilesystemTest.kt
I've implemented each of these without making recursive function calls. This
is very defensive; I'm attempting to prevent StackOverflowErrors for deep
paths.
> Filesystem.createDirectories and deleteRecursively

- okio-testing/src/commonMain/kotlin/okio/FakeFilesystem.kt
- okio/src/commonTest/kotlin/okio/AbstractFilesystemTest.kt
It was restored on flush, but it should have been readable before that.
> Fix a bug where FakeFilesystem.appendingSink cleared the file

- okio-testing/src/commonMain/kotlin/okio/FakeFilesystem.kt
- okio/src/commonMain/kotlin/okio/Filesystem.kt
- okio/src/commonMain/kotlin/okio/Path.kt
- okio/src/commonTest/kotlin/okio/FakeFilesystemTest.kt
- okio/src/commonTest/kotlin/okio/PathTest.kt
Also fix some bugs handling roots in the fake filesystem.
> Path.isRoot returns true for / and C:\

- okio-testing/src/commonMain/kotlin/okio/FakeFilesystem.kt
- okio/src/commonMain/kotlin/okio/-Platform.kt
- okio/src/commonTest/kotlin/okio/FakeFilesystemTest.kt
- okio/src/nonJvmMain/kotlin/okio/-Platform.kt
Including a stacktrace captured when the file was opened should
help to diagnose what fix is necessary.
> FakeFilesystem.checkNoOpenFiles() has better information

- okio-testing/src/commonMain/kotlin/okio/FakeFilesystem.kt
- okio/src/commonMain/kotlin/okio/Filesystem.kt
- okio/src/commonMain/kotlin/okio/Path.kt
- okio/src/commonTest/kotlin/okio/FakeFilesystemTest.kt
- okio/src/jsMain/kotlin/okio/Platform.kt
- okio/src/jvmMain/kotlin/okio/Platform.kt
- okio/src/jvmTest/java/okio/FilesystemJavaTest.java
- okio/src/nativeMain/kotlin/okio/Platform.kt
One gotcha with @ExperimentalFilesystem is that it doesn't impact Java callers.
We'll need to do that with documentation instead.
> Improve APIs for Java consumers

- okio-fakefilesystem/src/commonMain/kotlin/okio/fakefilesystem/FakeFileSystem.kt
- okio/src/commonTest/kotlin/okio/FakeFileSystemTest.kt
- okio/src/commonTest/kotlin/okio/ForwardingFileSystemTest.kt
Instead of having a single windows-vs-UNIX option, introduce individual
options that describe specific behavior, and functions to select UNIX
and Windows' options as a combo.
This permits a follow-up to forbid reading while writing, and also to
forbid multiple concurrent writers.
> Redesign FakeFileSystem's Windows limitations

- okio/src/commonMain/kotlin/okio/Path.kt
- okio/src/commonMain/kotlin/okio/internal/Path.kt
- okio/src/commonTest/kotlin/okio/PathTest.kt
- okio/src/jvmMain/kotlin/okio/Path.kt
- okio/src/jvmTest/java/okio/FileSystemJavaTest.java
- okio/src/nonJvmMain/kotlin/okio/Path.kt
This was an attempt to make Paths have a property that would
differentiate whether they follow Windows vs. UNIX rules. But
the consequence as that two relative paths, 'foo', and 'foo'
could be different because of the hidden state of the unused
slash.
Instead just look inside the path for the slash. In the case
where we're resolving two paths without either having any
slash characters internally, just use the platform slash.
> Remove the slash property from Path

- okio-zipfilesystem/README.md
- okio-zipfilesystem/build.gradle
- okio-zipfilesystem/gradle.properties
- okio-zipfilesystem/src/jvmMain/kotlin/okio/zipfilesystem/FixedLengthSource.kt
- okio-zipfilesystem/src/jvmTest/kotlin/okio/zipfilesystem/FixedLengthSourceTest.kt
- settings.gradle
The FixedLengthSource will be necessary with the ZIP implementation. When
reading an uncompressed slice we need to put a bound on the end of the
source. When reading a compressed slice we expect it to exhaust exactly
as expected.
> New zipfilesystem module and FixedLengthSource class

- okio-zipfilesystem/build.gradle
- okio-zipfilesystem/src/jvmMain/kotlin/okio/zipfilesystem/ZipEntry.kt
- okio-zipfilesystem/src/jvmMain/kotlin/okio/zipfilesystem/ZipFileSystem.kt
- okio-zipfilesystem/src/jvmMain/kotlin/okio/zipfilesystem/zip.kt
- okio-zipfilesystem/src/jvmTest/kotlin/okio/zipfilesystem/ZipBuilder.kt
- okio-zipfilesystem/src/jvmTest/kotlin/okio/zipfilesystem/ZipFileSystemTest.kt
I've decided that I can't use Java's built-in zip APIs to create complete-enough
zip files. These APIs target a subset of the zip spec and can't create data rich
enough for a good test suite.
In follow-up it might be useful to commit these zip files rather than creating
them on-demand. That approach should also make it possible to test Windows-originated
zip files on UNIX and vice-versa.
> Better tests for zip files

- okio-fakefilesystem/src/commonMain/kotlin/okio/fakefilesystem/FakeFileSystem.kt
- okio/src/commonMain/kotlin/okio/FileSystem.kt
- okio/src/commonTest/kotlin/okio/AbstractFileSystemTest.kt
We were previously returning absolute paths always, even when the
input directory was a relative path.
> Fix FakeFileSystem.list() to return relative paths

- okio-fakefilesystem/src/commonMain/kotlin/okio/fakefilesystem/FakeFileSystem.kt
- okio-nodefilesystem/src/jsMain/kotlin/okio/NodeJsFileSystem.kt
- okio-zipfilesystem/src/jvmMain/kotlin/okio/zipfilesystem/ZipFileSystem.kt
- okio/src/commonMain/kotlin/okio/FileHandle.kt
- okio/src/commonMain/kotlin/okio/FileSystem.kt
- okio/src/commonMain/kotlin/okio/ForwardingFileSystem.kt
- okio/src/jsMain/kotlin/okio/FileSystem.kt
- okio/src/jvmMain/kotlin/okio/JvmSystemFileSystem.kt
- okio/src/nativeMain/kotlin/okio/PosixFileSystem.kt
- okio/src/nonJsMain/kotlin/okio/FileSystem.kt
I'm hoping to get something close to the underlying file descriptor or file
handle abstraction in POSIX.
I am unsatisfied with the design of okio.Cursor and how it will work with
random-access reading and writing. I'm hoping to make this the successor to
that class, and to completely delete that class from our public API.
I am planning a follow up PR on FileSystem, FileSystem.open(Path) that
returns a FileHandle. I will also make FileSystem.source() and
FileSystem.sink() all delegate to FileSystem.open().
> FileHandle, for reading and writing, streaming and random access

- okio-fakefilesystem/src/commonMain/kotlin/okio/fakefilesystem/FakeFileSystem.kt
- okio-nodefilesystem/src/jsMain/kotlin/okio/NodeJsFileSystem.kt
- okio/src/commonMain/kotlin/okio/FileHandle.kt
- okio/src/commonMain/kotlin/okio/FileSystem.kt
- okio/src/commonMain/kotlin/okio/ForwardingFileSystem.kt
- okio/src/commonTest/kotlin/okio/AbstractFileSystemTest.kt
- okio/src/jsMain/kotlin/okio/FileSystem.kt
- okio/src/jvmMain/kotlin/okio/JvmFileHandle.kt
- okio/src/jvmMain/kotlin/okio/JvmSystemFileSystem.kt
- okio/src/jvmMain/kotlin/okio/ResourceFileSystem.kt
- okio/src/jvmMain/kotlin/okio/ZipFileSystem.kt
- okio/src/jvmMain/kotlin/okio/internal/zip.kt
- okio/src/jvmTest/kotlin/okio/FileHandleTestingFileSystem.kt
- okio/src/nativeMain/kotlin/okio/PosixFileSystem.kt
- okio/src/nonJsMain/kotlin/okio/FileSystem.kt
This is easier to use from Java (no boolean parameters). It also opens the
door to having a ReadWriteFileHandle subtype.
> Split open() into openReadOnly() and openReadWrite().

- okio/build.gradle.kts
- okio/src/commonMain/kotlin/okio/-Base64.kt
- okio/src/commonMain/kotlin/okio/internal/-Buffer.kt
- okio/src/commonMain/kotlin/okio/internal/-ByteString.kt
- okio/src/commonMain/kotlin/okio/internal/-Path.kt
- Marks all top level properties with `@SharedImmutabble` annotation in order to avoid error `kotlin.native.IncorrectDereferenceException: Trying to access top level value not marked as @ThreadLocal or @SharedImmutable from non-main thread
` when calling okio from background thread.
- Configure additional test tasks for native targets to run code in the background ([the same approach](https://github.com/Kotlin/kotlinx.coroutines/blob/1efc9f16a352632e6b632b4daab075ac882e661a/kotlinx-coroutines-core/build.gradle#L87-L102) was taken by kotlin.coroutines project).
> Fix using okio from background thread on Kotlin/Native targets

- okio/src/jvmMain/kotlin/okio/ResourceFileSystem.kt
- okio/src/jvmMain/kotlin/okio/internal/zip.kt
- okio/src/jvmTest/java/okio/ResourceFileSystemTest.kt
The resource file system could drag a lot of data into memory.
Omitting .class files from the index should save space.
This prevents .class files from being opened directly. I think
that's okay.
> Filter .class files from the ResourceFileSystem

- gradle.properties
- okio/src/commonMain/kotlin/okio/-Util.kt
- okio/src/commonMain/kotlin/okio/Buffer.kt
- okio/src/commonMain/kotlin/okio/ByteString.kt
- okio/src/commonMain/kotlin/okio/internal/-Buffer.kt
- okio/src/commonMain/kotlin/okio/internal/-ByteString.kt
- okio/src/commonMain/kotlin/okio/internal/-SegmentedByteString.kt
- okio/src/commonMain/kotlin/okio/internal/-Utf8.kt
- okio/src/commonTest/kotlin/okio/AbstractBufferedSinkTest.kt
- okio/src/commonTest/kotlin/okio/AbstractFileSystemTest.kt
This introduces a very ugly workaround to a limitation in the IR compiler
where default parameter values cannot be functions on the invoked object.
https://youtrack.jetbrains.com/issue/KT-45542
It also works around a bug in IR where Long.toString() returns the wrong
value.
https://youtrack.jetbrains.com/issue/KT-39891
Closes: https://github.com/square/okio/issues/910
> Support Kotlin/JS IR and Legacy JS

- okio/src/commonTest/kotlin/okio/AbstractFileSystemTest.kt
I observed this failure in CI:
>  expected 2021-05-29T22:15:58.995Z in 2021-05-29T22:15:59Z..2021-05-29T22:16:01Z
I can't tell if the problem is that the file system is using a different clock, or
if the time bounds are being rounded too much.
My best guess is that the CI filesystem is using a different clock from the test
and there's at least 5 milliseconds of clock skew between them.
> Provide even more information when FileSystem timestamps surprise

- buildSrc/src/main/kotlin/Dependencies.kt
- okio/src/commonTest/kotlin/okio/AbstractFileSystemTest.kt
Changelog:
- Updated versions.kotlin to 1.5.20
- Changelog for 1.5.20: https://kotlinlang.org/docs/whatsnew1520.html
- Changelog for 1.5.0: https://kotlinlang.org/docs/whatsnew15.html
- Changelog for 1.4.30: https://kotlinlang.org/docs/whatsnew1430.html
- Updated kotlinx-datetime from 0.1.1 to 0.2.1 since Kotlin 1.5.0 depends on datetime > 0.2.0
- Due to the changes to the experimental Duration inline value class
- Changelog: https://github.com/Kotlin/kotlinx-datetime/blob/master/CHANGELOG.md#021
- Changed expected values in tests due to hardcoded values of some updates around Kotlin JS/IR and Legacy JS APIs
Closes: #947
> Kotlin 1.5.20

- okio/src/jvmMain/kotlin/okio/FileSystem.kt
- okio/src/jvmMain/kotlin/okio/JvmOkio.kt
- okio/src/jvmMain/kotlin/okio/internal/ResourceFileSystem.kt
- okio/src/jvmTest/java/okio/internal/ResourceFileSystemTest.kt
My recent PRs to load all roots makes behavior better, but it causes the
file system to be initialized too eagerly. This makes every FileSystem user
pay for initialization of the ResourceFileSystem even if they don't use it.
> Make ResourceFileSystem initialize lazily

- okio/src/jvmMain/kotlin/okio/internal/zip.kt
- okio/src/jvmTest/java/okio/ZipFileSystemTest.kt
This is too common in practice.
> Don't crash on duplicate entries in a .zip file

- okio/src/commonMain/kotlin/okio/Path.kt
- okio/src/commonTest/kotlin/okio/AbstractFileSystemTest.kt
- okio/src/jvmMain/kotlin/okio/Path.kt
- okio/src/mingwX64Main/kotlin/okio/-WindowsPosixVariant.kt
- okio/src/nativeMain/kotlin/okio/-PosixVariant.kt
- okio/src/nativeMain/kotlin/okio/PosixFileSystem.kt
- okio/src/unixMain/kotlin/okio/-UnixPosixVariant.kt
Without this, files that contain 0x1a will be prematurely terminated.
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/fopen-wfopen?view=msvc-160
> Open files in binary mode on Windows

- okio/src/commonMain/kotlin/okio/ByteString.kt
- okio/src/commonMain/kotlin/okio/internal/-ByteString.kt
- okio/src/commonMain/kotlin/okio/internal/-SegmentedByteString.kt
- okio/src/commonTest/kotlin/okio/ByteStringTest.kt
- okio/src/jvmMain/kotlin/okio/ByteString.kt
- okio/src/jvmMain/kotlin/okio/SegmentedByteString.kt
- okio/src/nonJvmMain/kotlin/okio/ByteString.kt
- okio/src/nonJvmMain/kotlin/okio/SegmentedByteString.kt
I have a use-case for this in Wire and doing an intermediate copy is not
appropriate.
> ByteString.copyInto()

- buildSrc/src/main/kotlin/Dependencies.kt
This is great for downstream projects as kotlin.test is broken on
1.5.21 (multiplatform packaging issue) and the compiler is broken
on 1.5.30 (defaultfield verify error). With 1.5.31 everything should
work all on the same version.
> Upgrade to Kotlin 1.5.31

- okio-fakefilesystem/src/commonMain/kotlin/okio/fakefilesystem/FakeFileSystem.kt
- okio-fakefilesystem/src/commonMain/kotlin/okio/fakefilesystem/time.kt
- okio-nodefilesystem/src/main/kotlin/okio/NodeJsFileSystem.kt
- okio-testing-support/src/commonMain/kotlin/okio/AbstractFileSystemTest.kt
- okio/src/commonMain/kotlin/okio/FileMetadata.kt
- okio/src/commonMain/kotlin/okio/FileSystem.kt
- okio/src/commonMain/kotlin/okio/ForwardingFileSystem.kt
- okio/src/commonMain/kotlin/okio/Path.kt
- okio/src/commonMain/kotlin/okio/internal/-Path.kt
- okio/src/commonTest/kotlin/okio/FakeFileSystemTest.kt
- okio/src/jsMain/kotlin/okio/FileSystem.kt
- okio/src/jvmMain/kotlin/okio/FileSystem.kt
- okio/src/jvmMain/kotlin/okio/JvmSystemFileSystem.kt
- okio/src/jvmMain/kotlin/okio/NioSystemFileSystem.kt
- okio/src/jvmMain/kotlin/okio/Path.kt
- okio/src/jvmMain/kotlin/okio/ZipFileSystem.kt
- okio/src/jvmMain/kotlin/okio/internal/ResourceFileSystem.kt
- okio/src/jvmMain/kotlin/okio/internal/zip.kt
- okio/src/linuxX64Main/kotlin/okio/-LinuxX64PosixVariant.kt
- okio/src/mingwX64Main/kotlin/okio/-WindowsPosixVariant.kt
- okio/src/nativeMain/kotlin/okio/FileSystem.kt
- okio/src/nativeMain/kotlin/okio/PosixFileSystem.kt
- okio/src/nonJvmMain/kotlin/okio/Path.kt
This required significant rework to the internals of FakeFileSystem
which must now implement symlink-aware path resolution.
> Implement support for creating and traversing symlinks

- okio/src/appleMain/kotlin/okio/-ApplePosixVariant.kt
- okio/src/linuxX64Main/kotlin/okio/-LinuxX64PosixVariant.kt
- okio/src/mingwX64Main/kotlin/okio/-WindowsPosixVariant.kt
- okio/src/nativeMain/kotlin/okio/-PosixVariant.kt
- okio/src/nativeMain/kotlin/okio/PosixFileSystem.kt
- okio/src/unixMain/kotlin/okio/-UnixPosixVariant.kt
We were always appending to the end on FileHandle. This fix writes in
the appropriate place by changing open flags.
We weren't returning the symlink target.
Also fix file opens to be as atomic as possible on all UNIX systems.
> Fix two Linux bugs

- build-support/src/main/kotlin/platforms.kt
This is a followup to https://github.com/square/okio/pull/1027 and https://github.com/square/okio/pull/1028, and adds `watchosX64` (Apple watchOS 64-bit simulator for watchOS 7.0 and newer, on x86_64 platforms)
> Add watchosX64 target

- okio/src/jvmTest/java/okio/internal/ResourceFileSystemTest.kt
- okio/src/jvmTest/resources/okio/resourcefilesystem/non-ascii/ギリシア神話/Ἰλιάς
I'm not sure how to test Okio writing a similar file and assert that it matches the golden file.
Related to #1085
> FileSystem.RESOURCES test with special character named files

- gradle.properties
- okio/src/jvmMain/kotlin/okio/internal/zip.kt
- okio/src/jvmTest/java/okio/ZipFileSystemTest.kt
Zips can contain arbitrary data anywhere prior to the central directory including before any local file entry. Empty zips are now detected based on the file count from the central directory.
Closes #1094
> Do not expect zips to start with a local file header

- okio/src/jvmMain/kotlin/okio/ZipFileSystem.kt
> Fix override parameter name to match supertype

- okio/src/commonMain/kotlin/okio/internal/-Path.kt
Presumably the API should just be exposing `String.toPath(Boolean)` which delegates to `String.commonToPath(Boolean)`.
> Make `String.commonToPath(Boolean)` internal

- okio/build.gradle.kts
Time is now stable and duplicate resources are handled automatically.
> Remove build workarounds for old versions

- okio/src/jvmMain/kotlin/okio/ZipFileSystem.kt
- okio/src/jvmTest/java/okio/ZipFileSystemTest.kt
Per `canonicalize` documentation.
> Throw on canonincalization of paths which do not exists

- okio/src/appleMain/kotlin/okio/ByteString.kt
- okio/src/appleTest/kotlin/okio/AppleByteStringTest.kt
If you try to use `NSData.toByteString` with empty NSData method crashes with `kotlin.ArrayIndexOutOfBoundsException`
> Fix 'NSData.toByteString'

- build.gradle.kts
This should prevent Maven users from needing to change
their dependencies from okio to okio-jvm. More importantly,
it should also prevent them from inadvertently getting two
different Okio JVM artifacts on their classpaths at once.
> Make pom.xml depend on the JVM artifact

- okio/src/commonMain/kotlin/okio/BufferedSink.kt
- okio/src/commonMain/kotlin/okio/BufferedSource.kt
- okio/src/jvmMain/kotlin/okio/BufferedSink.kt
- okio/src/jvmMain/kotlin/okio/BufferedSource.kt
- okio/src/nonJvmMain/kotlin/okio/BufferedSink.kt
- okio/src/nonJvmMain/kotlin/okio/BufferedSource.kt
These interfaces are not meant for third-party implementation. The `Buffer` type and the type returned by `.buffer()` are the only valid implementations.
> Seal the `BufferedSource`/`BufferedSink` hierarchy

- okio/src/jvmMain/kotlin/okio/JvmSystemFileSystem.kt
- okio/src/jvmTest/kotlin/okio/JvmSystemFileSystemTest.kt
If we use `JvmSystemFileSystem.deleteRecursively()` to delete a folder that contains sub-files, then interrupt the thread, we want the delete action will be interrupted earlier.
> Check thread isInterrupted before deleting on JvmSystemFileSystem

- gradle.properties
Pretty sure this is not needed anymore as it was fixed by Sonatype. I've been running my projects without this and it's working fine these days.
> Remove workaround and publish sha256/sha512 checksums

- build.gradle.kts
Changes from this PR all work to increase the performance of Gradle builds for the project. Below is a summary of what these changes are and why they are recommended…
1.) Ignore the attribute ‘Bnd-LastModified’ from metadata files. 
Some snapshot jars (example okio-jvm-#.#.#-SNAPSHOT.jar) that are built within the project contain manifest files with the attribute ‘Bnd-LastModified’. This property is set to always set to the timestamp of the build, meaning that those manifest files will always be different for each build regardless of if anything else changes in the project. The end result is multiple Gradle tasks that have to be executed despite them being cacheable.
This was resolved by telling Gradle to ignore changes to the attribute ‘Bnd-LastModified’ for any manifest files that exist …
> Increase the performance of Gradle builds.

- .github/workflows/build.yml
Ahead of some testing with Loom on 19. https://github.com/square/okio/pull/1176
Add regular builds in for 18 + 19.
> Run tests on JDK 18 + 19

- docs/css/app.css
- mkdocs.yml
Adds a light/dark mode toggle to the docs
Live demo: https://asemy.github.io/okio/
Documentation here: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle
Example config here: https://github.com/squidfunk/mkdocs-material/blob/2569d4f0884b9fe3be934215ce0cfddf8efc94b8/mkdocs.yml#L60-L72
This PR is based on https://github.com/cashapp/sqldelight/pull/3637
> mkdocs: add light/dark mode toggle

- .github/workflows/build.yml
This is motivated by an accute problem with OpenJDK 10, which is consistently failing in CI for reasons wholy unrelated to Okio.
> Configure project :android-test
Unable to detect AGP versions for included builds. All projects in the build should use the same AGP version. Class name for the included build object: org.gradle.composite.internal.DefaultIncludedBuild$IncludedBuildImpl_Decorated.
e: /home/runner/work/okio/okio/android-test/build.gradle.kts:18:1: Unresolved reference: android
It's likely Gradle or AGP or something doesn't work on Java 10, even though it does work on Java 8, Java 9, Java 11, and Java 12.
I'm not interested in debugging this problem; the right fix for it is 'Upgrade to a newer JDK'.
I've specifically dropped unmaintained JDKs according to this page: …
> Don't do CI builds for obsolete JDKs

- okio-testing-support/src/commonMain/kotlin/okio/AbstractFileSystemTest.kt
I've been observing failures like this:
expected 2022-12-31T16:00:40.999Z in 2022-12-31T16:00:41Z..2022-12-31T16:00:43Z (relaxed from 2022-12-31T16:00:41.002314Z..2022-12-31T16:00:41.002365Z)
> Attempt to make filesystem tests less flaky

- okio-nodefilesystem/src/main/kotlin/okio/NodeJsFileSystem.kt
The c in ctime means changed, not created.
Closes: https://github.com/square/okio/issues/1215
> Use birthtimeMs, not ctimeMs

- .github/workflows/build.yml
Same thing we're using in a bunch of repos now.
> Do not build non-master branches unless manually dispatched

- okio/src/commonMain/kotlin/okio/Buffer.kt
- okio/src/jvmMain/kotlin/okio/Buffer.kt
Been wondering for some time why there was both [copy](https://square.github.io/okio/3.x/okio/okio/okio/-buffer/index.html#-18127258%2FFunctions%2F-1473893935) and [clone](https://square.github.io/okio/3.x/okio/okio/okio/-buffer/index.html#1052611650%2FFunctions%2F1773621890).  Looks like `clone` is a JVM only thing and there's no other reason than implementing `Cloneable`? Hoping this can clear the confusion. Also added a note about `copy()` initially sharing the ByteArrays.
> Minor edits to the Buffer.copy/clone Kdoc

- okio/src/commonMain/kotlin/okio/Buffer.kt
- okio/src/commonTest/kotlin/okio/UnsafeCursorTest.kt
- okio/src/nonJvmMain/kotlin/okio/Buffer.kt
While docs recommend to use `Closable.use` extension to manage UnsafeCursor as resource, `Closable.use` extension is not applicable to UnsafeCursor because UnsafeCursor does not implement Closable interface.
This PR contains:
1. Multiplatform test to ensure Unsafe Cursor implements Closeable interface
2. Commit that fixes #1238 and ensures the test above
> Make UnsafeCursor implement Closable interface in multiplatform (Fixes #1238)

- build-support/src/main/kotlin/bom.kt
- okio-assetfilesystem/build.gradle.kts
- okio-bom/build.gradle.kts
Closes: https://github.com/square/okio/issues/1121
> Collect BOM constraints automatically

- okio-testing-support/src/commonMain/kotlin/okio/AbstractFileSystemTest.kt
This will force new implementation to pay attention.
> Invert supportsFileHandle and supportsSymlink

- okio/src/jvmMain/kotlin/okio/GzipSource.kt
- okio/src/jvmTest/kotlin/okio/GzipKotlinTest.kt
We treated this short value as unsigned and it should have been treated as signed.
> Fix a bug where xlen larger than 0x7fff was rejected

- okio/src/nativeMain/kotlin/okio/SizetVariant.kt
Signed integer constant cannot be automatically converted to unsigned integer anymore after Kotlin 1.9.0.
See https://youtrack.jetbrains.com/issue/KT-56583 for detail
> Fix conversion of signed constants to unsigned

- .github/workflows/build.yml
It's no longer necessary.
Closes: https://github.com/square/okio/issues/1286
> Drop the publish-windows task

- okio-testing-support/src/nonWasmMain/kotlin/okio/AbstractFileSystemTest.kt
- okio/src/mingwX64Main/kotlin/okio/WindowsFileHandle.kt
- okio/src/unixMain/kotlin/okio/UnixFileHandle.kt
If you try to use `FileHandle.read/write` with empty ByteArray on Native, method crashes with kotlin.ArrayIndexOutOfBoundsException.
> Fix FileHandle read/write with empty array

- okio-testing-support/src/nonWasmMain/kotlin/okio/AbstractFileSystemTest.kt
- okio/src/jvmMain/kotlin/okio/NioFileSystemWrappingFileSystem.kt
which was not detected before because relative tests uses DOT
> NioFS: fix relative paths when listing a dir

- .github/workflows/build.yml
Snapshot publications fail because of this. I think we'll remember to take it out once ready to ship?
> Exclude wasm from the publish job until it's ready

- okio-wasifilesystem/src/wasmMain/kotlin/okio/WasiFileSystem.kt
- okio-wasifilesystem/src/wasmMain/kotlin/okio/internal/preview1/Filetype.kt
- okio-wasifilesystem/src/wasmMain/kotlin/okio/internal/preview1/LookupFlags.kt
- okio-wasifilesystem/src/wasmMain/kotlin/okio/internal/preview1/Preview1.kt
- okio-wasifilesystem/src/wasmTest/kotlin/okio/WasiTest.kt
This doesn't yet handle no such file.
> Implement FileMetadata for WasiFileSystem

- okio-wasifilesystem/build.gradle.kts
The new okio-wasifilesystem module is a multiplatform module with a single artifact. This configuration is broken on the latest version of Dokka.
https://github.com/Kotlin/dokka/issues/3038
> Attempt to fix publishing with WASM

- okio-wasifilesystem/src/wasmMain/kotlin/okio/WasiFileSystem.kt
- okio-wasifilesystem/src/wasmMain/kotlin/okio/internal/preview1/Fdflags.kt
- okio-wasifilesystem/src/wasmMain/kotlin/okio/internal/preview1/Preview1.kt
- okio-wasifilesystem/src/wasmTest/kotlin/okio/WasiTest.kt
Also appendingSink
Also deleting directories
I'm very eager to bring AbstractFileSystemTest online for this.
> WasiFileSystem.canonicalize

- okio-wasifilesystem/build.gradle.kts
- okio-wasifilesystem/src/wasmMain/kotlin/okio/WasiFileSystem.kt
- okio-wasifilesystem/src/wasmMain/kotlin/okio/internal/preview1/Preview1.kt
- okio-wasifilesystem/src/wasmTest/kotlin/okio/WasiFileSystemPreopensTest.kt
- okio-wasifilesystem/src/wasmTest/kotlin/okio/WasiFileSystemTest.kt
- okio-wasifilesystem/src/wasmTest/kotlin/okio/WasiTest.kt
I need to find a proper document explaining how this all works. As is it works but is not following a proper spec.
> Add API to choose non-default preopens

- okio-testing-support/src/commonMain/kotlin/okio/AbstractFileSystemTest.kt
- okio-wasifilesystem/src/wasmMain/kotlin/okio/WasiFileSystem.kt
Creating absolute symlinks is broken in WASI. This also works better for preopens.
> Only create relative symlinks in WasiFileSystem

- okio-wasifilesystem/build.gradle.kts
Attempting to run dokkaHtml causes a crash at configuration time that can't be suppressed more precisely.
> Attempt to fix website publishing

- okio/src/jvmMain/kotlin/okio/DeflaterSink.kt
- okio/src/jvmTest/kotlin/okio/DeflaterSinkTest.kt
From https://github.com/square/okhttp/issues/6719
Not sure it isn't a programming bug, but even if so, IOException seems appropriate.
> Handle JDK Deflater throwing NPE

- okio/src/main/java/okio/GzipSource.java
- okio/src/test/java/okio/GzipSourceTest.java
Backported from 81bce1a30af244550b0324597720e4799281da7b
Backported for 1.x. Please consider releasing this fix for 1.x stream so we don't need to update to 3.4.0 since it's a big jump.
> Fix a bug where xlen larger than 0x7fff was rejected (1.x)

- okio/src/jvmMain/kotlin/okio/ZipFileSystem.kt
- okio/src/jvmTest/kotlin/okio/FileLeakTest.kt
Discovered this issue via the [wire](https://github.com/square/wire) project.
The issue here is that the `ZipFileSystem` creates a `Source` object, which is then returned out of the `use` lambda, which the lambda is supposed to close the `FileHandle` that is created, however, because the `Source` object had not been closed, the `FileHandle` remains open.
```kotlin
val source = fileSystem.openReadOnly(zipPath).use { fileHandle ->
fileHandle.source(entry.offset).buffer()
}
return source.readLocalHeader(basicMetadata)
```
Going into a bit more detail, the `openStreamCount` is not `0` because the `Source` object wasn't closed, so we never close the underlying `RandomAccessFile` that was opened.
```kotlin
@Throws(IOException::class)
final override fun close() {
lock.withLock {
if (closed) …
```
> Fix file leak when using `metadata` functions

- gradle/libs.versions.toml
- okio-fakefilesystem/build.gradle.kts
Partially addresses: https://github.com/square/okio/issues/1388
Support for `wasmWasi` is blocked by `kotlinx.datetime` support: https://github.com/Kotlin/kotlinx-datetime/issues/324
> Add support for wasmJs in okio-fakefilesystem.

- okio/src/jvmMain/kotlin/okio/Timeout.kt
The function returns a non-positive value if the call timed out, so there's no need to measure that independently.
> Reduce calls to nanoTime in Timeout.awaitSignal()

- okio/api/okio.api
- okio/src/jvmMain/kotlin/okio/ForwardingTimeout.kt
- okio/src/jvmMain/kotlin/okio/Timeout.kt
- okio/src/jvmTest/kotlin/okio/AwaitSignalTest.kt
- okio/src/jvmTest/kotlin/okio/TimeoutFactory.kt
- okio/src/jvmTest/kotlin/okio/WaitUntilNotifiedTest.kt
This needs lock-checking functions to be forwarded also, as the timeout now holds more state than before.
> Implement ForwardingTimeout.cancel()

- okio/api/okio.api
- okio/src/jvmMain/kotlin/okio/AsyncTimeout.kt
- okio/src/jvmTest/kotlin/okio/AsyncTimeoutTest.kt
This is a simple implementation that uses 3 booleans to keep state (inQueue, isCanceled, hadTimeoutWhenCanceled). I'd like to do a follow-up change to replace 3 booleans with a proper state variable, especially since that eliminates some impossible states (like inQueue and isCanceled).
> Implement AsyncTimeout.cancel()

- okio/api/okio.api
- okio/src/jvmMain/kotlin/okio/AsyncTimeout.kt
Previously we had 3 boolean state variables to track 4 possible states. That was more complex than necessary.
> Use a state machine to implement AsyncTimeout

- okio/src/commonMain/kotlin/okio/Options.kt
The array size is already derived from the buffer size.
> Don't check buffer exhaustion while filling ints

- okio/src/nativeMain/kotlin/okio/Cinterop.kt
- okio/src/nativeTest/kotlin/okio/ByteStringCinteropTest.kt
> Add `readByteString` cinterop extension

- okio/src/jvmMain/kotlin/okio/internal/ResourceFileSystem.kt
- okio/src/jvmTest/kotlin/okio/FileLeakTest.kt
This fix is for #1364. It prevents the issue where `ClassLoader.getResourceAsStream()` caches an open file due to `URLConnection.openStream()` works. More details in https://github.com/square/okio/issues/1364#issuecomment-1758260314.
> Prevent caching URLConnection files in ResourceFileSystem

- okio/src/nativeMain/kotlin/okio/internal/-ZlibNative.kt
- okio/src/zlibMain/kotlin/okio/GzipSink.kt
- okio/src/zlibMain/kotlin/okio/GzipSource.kt
- okio/src/zlibMain/kotlin/okio/internal/-Zlib.kt
- okio/src/zlibTest/kotlin/okio/GzipKotlinTest.kt
- okio/src/zlibTest/kotlin/okio/GzipSinkTest.kt
- okio/src/zlibTest/kotlin/okio/GzipSourceTest.kt
This layers on top of the newly-multiplatformed Inflater, Deflater, and CRC32.
> Make GzipSink and GzipSource multiplatform

- okio/src/commonTest/kotlin/okio/OkioTesting.kt
- okio/src/jvmMain/kotlin/okio/internal/-ZlibJvm.kt
- okio/src/jvmMain/kotlin/okio/internal/ZipFiles.kt
- okio/src/jvmTest/kotlin/okio/JvmTesting.kt
- okio/src/nativeMain/kotlin/okio/internal/-ZlibNative.kt
- okio/src/nonJvmTest/kotlin/okio/NonJvmTesting.kt
- okio/src/zlibMain/kotlin/okio/internal/-Zlib.kt
- okio/src/zlibTest/kotlin/okio/internal/DatePartsToEpochMillisTest.kt
This might be foolish. The total amount of new code is
relatively small (45 lines of code), but that code does
something we don't otherwise want to be doing in Okio -
date math.
But this unblocks implementing ZipFileSystem in Kotlin/Native.
> Handle DOS dates in Kotlin/Multiplatform

- okio/src/commonMain/kotlin/okio/Okio.kt
- okio/src/nonWasmTest/kotlin/okio/UseTest.kt
> Fix `Closeable.use` `NullPointerException`

- .github/workflows/build.yml
Android and macOS builds are much faster for now.
https://github.blog/changelog/2023-02-23-hardware-accelerated-android-virtualization-on-actions-windows-and-linux-larger-hosted-runners
https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source
> Speed up CI

- okio/src/zlibMain/kotlin/okio/ZipFileSystem.kt
Currently, it just seems broken:
But I think this should fix it.
> Correct documentation links in ZipFileSystem.kt

- build.gradle.kts
- gradle/libs.versions.toml
- okio-fakefilesystem/build.gradle.kts
- okio/build.gradle.kts
Just the bare minimum to get upgraded to bnd 7.0.0
Fixes https://github.com/square/okio/pull/1363
> Upgrade bnd

- okio/src/commonMain/kotlin/okio/Buffer.kt
- okio/src/commonMain/kotlin/okio/ByteString.kt
These annotations are unnecessary and break under Kotlin -language-mode=2.0
> Remove @JvmField uses from commonMain

- okio/build.gradle.kts
- okio/src/jvmTest/hashFunctions
It doesn't work on Windows platform
> Avoid use symlink in project file

- okio/src/commonTest/kotlin/okio/HashingTest.kt
some test cases for Hmac SHA compared sha values instead of hmac sha values.
> fix(common): some HMacSHA tests compared sha values

- okio/src/jvmMain/kotlin/okio/RealBufferedSource.kt
Avoid unnecessary memory copying, during transfer data between streams.
> Implement transferTo method in RealBufferedSource.inputStream

- .gitignore
- android-test/build.gradle.kts
- build-support/build.gradle.kts
- build-support/settings.gradle.kts
- gradle/libs.versions.toml
- kotlin-js-store/yarn.lock
- okio-testing-support/src/commonMain/kotlin/okio/TestingCommon.kt
- okio-testing-support/src/wasmMain/kotlin/okio/TestingWasm.kt
- okio-wasifilesystem/build.gradle.kts
- okio/src/commonMain/kotlin/okio/Buffer.kt
- okio/src/commonMain/kotlin/okio/HashingSink.kt
- okio/src/commonMain/kotlin/okio/HashingSource.kt
- okio/src/commonMain/kotlin/okio/RealBufferedSink.kt
- okio/src/commonMain/kotlin/okio/RealBufferedSource.kt
- okio/src/jvmMain/kotlin/okio/Buffer.kt
- okio/src/jvmMain/kotlin/okio/DeflaterSink.kt
- okio/src/jvmMain/kotlin/okio/HashingSink.kt
- okio/src/jvmMain/kotlin/okio/HashingSource.kt
- okio/src/jvmMain/kotlin/okio/InflaterSource.kt
- okio/src/jvmMain/kotlin/okio/RealBufferedSink.kt
- okio/src/jvmMain/kotlin/okio/RealBufferedSource.kt
- okio/src/nativeMain/kotlin/okio/DeflaterSink.kt
- okio/src/nativeMain/kotlin/okio/InflaterSource.kt
- okio/src/nonJvmMain/kotlin/okio/Buffer.kt
- okio/src/nonJvmMain/kotlin/okio/HashingSink.kt
- okio/src/nonJvmMain/kotlin/okio/HashingSource.kt
- okio/src/nonJvmMain/kotlin/okio/RealBufferedSink.kt
- okio/src/nonJvmMain/kotlin/okio/RealBufferedSource.kt
- okio/src/zlibMain/kotlin/okio/DeflaterSink.kt
- okio/src/zlibMain/kotlin/okio/InflaterSource.kt
This requires some boilerplate on function declarations.
> Build with Kotlin 2.0.21

- build.gradle.kts
- gradle/libs.versions.toml
- okio/build.gradle.kts
- okio/src/commonTest/kotlin/okio/BufferedSourceFactory.kt
- okio/src/jvmTest/kotlin/okio/AwaitSignalTest.kt
- okio/src/jvmTest/kotlin/okio/BufferCursorKotlinTest.kt
- okio/src/jvmTest/kotlin/okio/BufferCursorTest.kt
- okio/src/jvmTest/kotlin/okio/BufferedSinkTest.kt
- okio/src/jvmTest/kotlin/okio/BufferedSourceTest.kt
- okio/src/jvmTest/kotlin/okio/ByteStringJavaTest.kt
- okio/src/jvmTest/kotlin/okio/CipherAlgorithm.kt
- okio/src/jvmTest/kotlin/okio/CipherSinkTest.kt
- okio/src/jvmTest/kotlin/okio/CipherSourceTest.kt
- okio/src/jvmTest/kotlin/okio/InflaterSourceTest.kt
- okio/src/jvmTest/kotlin/okio/ReadUtf8LineTest.kt
- okio/src/jvmTest/kotlin/okio/WaitUntilNotifiedTest.kt
- okio/src/jvmTest/kotlin/okio/internal/HmacTest.kt
It supports Kotlin/Multiplatform.
https://github.com/cashapp/burst
> Adopt Burst for parameterized tests

- okio/build.gradle.kts
- okio/src/commonMain/kotlin/okio/Okio.kt
- okio/src/jsMain/kotlin/okio/FileSystem.kt
- okio/src/jvmMain/kotlin/okio/-JvmPlatform.kt
- okio/src/jvmMain/kotlin/okio/FileSystem.kt
- okio/src/nativeMain/kotlin/okio/FileSystem.kt
- okio/src/nonJvmMain/kotlin/okio/NonJvmPlatform.kt
- okio/src/wasmMain/kotlin/okio/FileSystem.kt
> Add contract for action/block

- build.gradle.kts
We get Wasm GC in the standard distribution now.
> Don't use a NodeJS canary build

- okio/src/jvmMain/kotlin/okio/DeflaterSink.kt
- okio/src/jvmMain/kotlin/okio/internal/-ZlibJvm.kt
Even though the content of this array isn't read, it looks like deflater may still interfere by making a pair of calls to GetPrimitiveArrayCritical + ReleasePrimitiveArrayCritical.
Closes: https://github.com/square/okio/issues/1608
> Clear the deflater's byte array reference

- okio/api/okio.api
- okio/src/commonMain/kotlin/okio/Buffer.kt
- okio/src/commonMain/kotlin/okio/BufferedSource.kt
- okio/src/commonMain/kotlin/okio/RealBufferedSource.kt
- okio/src/commonMain/kotlin/okio/internal/Buffer.kt
- okio/src/commonMain/kotlin/okio/internal/RealBufferedSource.kt
- okio/src/jvmMain/kotlin/okio/Buffer.kt
- okio/src/jvmMain/kotlin/okio/BufferedSource.kt
- okio/src/jvmMain/kotlin/okio/RealBufferedSource.kt
- okio/src/jvmTest/kotlin/okio/BufferedSourceTest.kt
- okio/src/nonJvmMain/kotlin/okio/Buffer.kt
- okio/src/nonJvmMain/kotlin/okio/BufferedSource.kt
- okio/src/nonJvmMain/kotlin/okio/RealBufferedSource.kt
This is surprisingly interesting. To minimize unnecessary reads for toIndex it is necessary to check whether a prefix of the query matches a suffix of the currently-loaded data.
This read-avoidance is useful in practice. When doing HTTP multipart decoding the caller may scan for a boundary separator with a bounded range, and we don't want to block reading when doing so won't impact the result of the call.
> New API, BufferedSource.indexOf(ByteString, fromIndex, toIndex)

- .github/workflows/build.yml
- .github/workflows/release.yaml
- CHANGELOG.md
- build.gradle.kts
- docs/index.md
See (internally) http://go/central-portal-migration-com-squareup for context.
> Migrate to Sonatype Central Portal

- okio/api/okio.api
- okio/src/jvmMain/kotlin/okio/JvmOkio.kt
- okio/src/jvmMain/kotlin/okio/internal/PipeSocket.kt
- okio/src/jvmTest/kotlin/okio/SocketTest.kt
I'm using Array<Socket> instead of Pair<Socket, Socket> because Array is _slightly_ more friendly to Java-language consumers.
> New API, inMemorySocketPair()

- okio-fakefilesystem/build.gradle.kts
- okio-fakefilesystem/src/commonMain/kotlin/okio/fakefilesystem/FakeFileSystem.kt
- okio-fakefilesystem/src/commonMain/kotlin/okio/fakefilesystem/FileMetadataCommon.kt
- okio-fakefilesystem/src/jvmMain/kotlin/okio/fakefilesystem/FileMetadataJvm.kt
- okio-fakefilesystem/src/nonJvmMain/kotlin/okio/fakefilesystem/FileMetadataNonJvm.kt
Okio was broken when running on Kotlin before 2.1.20. The failure mode was too severe - a crash at runtime! And this is for code that worked just fine on Kotlin 2.0.x.
java.lang.NoSuchMethodError: 'kotlin.time.Clock kotlin.internal.PlatformImplementations.getSystemClock()'
at kotlin.time.InstantJvmKt.<clinit>(InstantJvm.kt:12)
at kotlin.time.Clock$System.now(Clock.kt:60)
at kotlinx.datetime.Clock$System.now(DeprecatedClock.kt:89)
at okio.fakefilesystem.-Time.defaultClockNowMillis_delegate$lambda$2(FileMetadataCommon.kt:70)
at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
at okio.fakefilesystem.-Time.getDefaultClockNowMillis(FileMetadataCommon.kt:65)
at okio.fakefilesystem.FakeFileSystem.<init>(FakeFileSystem.kt:72)
The failure would occur anywhere we were running Okio's …
> Don't use Clock.System on an JVM release

- okio/src/jvmMain/kotlin/okio/internal/DefaultSocket.kt
- okio/src/jvmTest/kotlin/okio/SocketTest.kt
I was looking into migrating OkHttp to use Okio's
Socket internally and I came across a small behavior change - previously we were getting the stream once and reusing it on each call, but now Okio is getting the stream on each access.
With this change the Socket.asOkioSocket() API behaves more consistently with Socket.source() and Socket.sink().
> Get Socket.inputStream and outputStream eagerly
