okio/src/main/java/okio/ByteString.java
okio/src/test/java/okio/ByteStringTest.java

Add ByteString#substring methods

---

okio/src/main/java/okio/Buffer.java
okio/src/main/java/okio/BufferedSink.java
okio/src/main/java/okio/BufferedSource.java
okio/src/main/java/okio/RealBufferedSink.java
okio/src/main/java/okio/RealBufferedSource.java
okio/src/test/java/okio/BufferedSinkTest.java
okio/src/test/java/okio/BufferedSourceTest.java

Refs #97.
Use it. Or don't. Was good fun writing/exploring the many ways to do these things.

Add support for reading and writing longs as stringy values.

---

okio/src/main/java/okio/Buffer.java
okio/src/main/java/okio/RealBufferedSource.java
okio/src/test/java/okio/BufferedSourceTest.java

They are neither necessary nor sufficient.

Kill digit counts.

---

okio/src/main/java/okio/Base64.java
okio/src/main/java/okio/ByteString.java
okio/src/test/java/okio/ByteStringTest.java

Add support for URL-safe base64 encoding.

---

okio/src/main/java/okio/ByteString.java
okio/src/test/java/okio/ByteStringTest.java

Add convenience methods for MD5 and SHA-256 hashes.

---

okio/src/main/java/okio/SegmentedByteString.java

We're going to need a better mechanism to test this. Perhaps following
the @Parameterized example we're already using for other APIs that have
multiple implementations.

Handle new ByteString APIs in SegmentedByteString.

---

okio/src/main/java/okio/Okio.java

I blundered the formatting fixing pguilbot's code. This fixes that.

Actually ignore expected AssertionError.

---

okio/src/main/java/okio/Segment.java

We've heard reports that this dramatically increases throughput
for some applications.

Try 8 KiB segments.

---

okio/pom.xml
pom.xml

This reverts commit d4da5cce2cd21383d75f171188575d272a353e6c.

Revert "Add OSGi metadata to Okio"

---

okio/src/main/java/okio/Segment.java
okio/src/test/java/okio/BufferedSourceTest.java

Otherwise we end up with long chains of short segments, which is its own
performance problem.

Don't share segments if doing so only saves a small copy.

---

okio/src/main/java/okio/Buffer.java
okio/src/main/java/okio/RealBufferedSource.java
okio/src/test/java/okio/BufferedSourceTest.java

Previously the algorithm that did this was extremely inefficient, and had worst
case runtime of O(N * S * S) for N is size of the bytestring and S is the number
of segments.
The new code runs in O(N * S). It accomplishes this by not starting each
search at the first segment, which could occur many times when called by
RealBufferedSource.

Make Source.indexOf(ByteString) significantly faster.

---

okio/src/main/java/okio/BufferedSource.java

Closes: https://github.com/square/okio/issues/172

Add some examples to buffered source read methods.

---

okio/src/main/java/okio/ByteString.java
okio/src/main/java/okio/SegmentedByteString.java
okio/src/test/java/okio/ByteStringTest.java

Closes https://github.com/square/okio/issues/159

Implement indexOf(), startsWith(), and endsWith().

---

okio/src/main/java/okio/Buffer.java
okio/src/main/java/okio/BufferedSource.java
okio/src/main/java/okio/RealBufferedSource.java
okio/src/test/java/okio/BufferedSourceTest.java

Add rangeEquals to BufferedSource.

---

okio/src/main/java/okio/GzipSink.java

Configure compress level for gzip sink

---

okio/src/test/java/okio/AsyncTimeoutTest.java
okio/src/test/java/okio/GzipSinkTest.java
okio/src/test/java/okio/GzipSourceTest.java
okio/src/test/java/okio/LargeStreamsTest.java
okio/src/test/java/okio/MockSink.java
okio/src/test/java/okio/SocketTimeoutTest.java
okio/src/test/java/okio/TestUtil.java

Attempting to reproduce https://github.com/square/okio/issues/250

Add some tests for reading very large streams.

---

okio/src/main/java/okio/ByteString.java
okio/src/main/java/okio/SegmentedByteString.java
okio/src/test/java/okio/ByteStringTest.java

Closes: https://github.com/square/okio/issues/248

APIs on ByteString to encode and decode any charset.

---

okio/src/test/java/okio/ByteStringTest.java

Also update some tests to make sure they're using the factory.

Add an extreme SegmentedByteString variant for testing.

---

okio/src/main/java/okio/Buffer.java
okio/src/main/java/okio/ByteString.java
okio/src/main/java/okio/HashingSink.java
okio/src/test/java/okio/HashingSinkTest.java
okio/src/test/java/okio/HashingTest.java

Add sha-512 hash and hmac support

---

README.md

Is this too much ceremony for a README sample?

Close BufferedSource in README sample

---

.travis.yml
okio/src/test/java/okio/ByteStringTest.java
okio/src/test/java/okio/TestUtil.java
pom.xml

Note: We'll have the same problem as https://github.com/square/okhttp/pull/3161#issuecomment-279595790 here.

Add error-prone compiler.

---

README.md

Update the README - this is longer a "new" library

---

pom.xml
samples/pom.xml
samples/src/main/java/okio/samples/Randoms.java

With UnsafeCursor I'm going to need some real samples. Might as well get
started with that.

Add an initial Okio code sample.

---

okio/src/main/java/okio/Buffer.java
okio/src/test/java/okio/BufferCursorTest.java

This is intended to be useful when integrating APIs like Cipher that need
a contiguous space to write data into.

New API, UnsafeCursor.expandBuffer().

---

pom.xml
samples/pom.xml
samples/src/main/java/okio/samples/SourceMarker.java
samples/src/test/java/okio/samples/SourceMarkerTest.java

This also adds a test case for the sample.
The sample uses ideas and tests from Picasso's MarkableInputStream.

New sample: SourceMarker.

---

README.md
samples/build.gradle
samples/src/main/java/okio/samples/SocksProxyServer.java

I chose a real network protocol here, which makes the example more complex
than I'd prefer, but it's also more representative of what real code would
need to do.

Networking recipe.

---

okio/jvm/src/main/java/okio/Buffer.kt

I was hoping I could use an inline function + destructuring return to do this.
Unfortunately that approach always allocates

Share code when seeking to a specific segment

---

okio/jvm/build.gradle
okio/jvm/src/main/java/okio/Buffer.kt
okio/jvm/src/main/java/okio/ByteString.kt
okio/jvm/src/main/java/okio/Options.kt
okio/jvm/src/main/java/okio/RealBufferedSource.kt
okio/jvm/src/main/java/okio/SegmentedByteString.kt
okio/jvm/src/test/java/okio/OptionsTest.kt
okio/jvm/src/test/java/okio/TestUtil.kt

Change ByteString.size from fun to val

---

okio/jvm/src/main/java/okio/Options.kt
okio/jvm/src/test/java/okio/OptionsTest.kt

We had two N*N loops here. We can do better.

Avoid O(N*N) loops constructing Options

---

gradle.properties

Enforce UTF-8 file encoding

---

okio/jvm/build.gradle
okio/jvm/src/main/java/okio/ByteString.kt

Use JvmName with ByteString.get, hide ByteString.getByte

---

okio/jvm/src/main/java/okio/ByteString.kt
okio/jvm/src/main/java/okio/platform.kt
okio/src/main/kotlin/okio/ByteString.kt
okio/src/main/kotlin/okio/common/ByteString.kt
okio/src/main/kotlin/okio/platform.kt

Crossplatform ByteString implementation

---

okio/jvm/src/main/java/okio/ByteString.kt
okio/jvm/src/main/java/okio/platform.kt
okio/src/main/kotlin/okio/Base64.kt
okio/src/main/kotlin/okio/common/ByteString.kt
okio/src/main/kotlin/okio/platform.kt

Crossplatform Base64

---

.travis.yml

Update sonatype user/pass environment variables for Gradle.

---

okio/js/build.gradle

Use Mocha for JS unit tests

---

okio/src/main/kotlin/okio/platform.kt

Update blocking issue link for platform-specific annotations

---

.travis.yml
build.gradle
okio/js/src/main/kotlin/okio/ByteString.kt
okio/jvm/src/main/java/okio/Buffer.kt
okio/jvm/src/main/java/okio/ByteString.kt
okio/jvm/src/test/java/okio/ByteStringTest.java
okio/jvm/src/test/java/okio/TestUtil.kt
okio/native/build.gradle
okio/native/src/main/kotlin/okio/ByteString.kt
okio/native/src/main/kotlin/okio/platform.kt
okio/src/main/kotlin/okio/Utf8.kt
okio/src/main/kotlin/okio/common/ByteString.kt
settings.gradle

Fixes #453 
Not sure if this issue was really up for grabs but I've been dipping my toe in Kotlin/Native a little and thought this would be a good first exercise.

Implement ByteString for Kotlin/Native

---

okio/jvm/src/test/java/okio/BufferedSourceTest.java

Tracking ideas from https://github.com/square/okio/pull/321

Add a BufferedSourceTest that uses small segments.

---

okio/jvm/src/test/java/okio/PipeKotlinTest.kt

One little thing I discovered: when calling fold() we move data from
the pipe to the new Sink. If there's a failure delivering this data
to the new sink that data is lost forever! We can't put it back in
the Pipe (it may have since grown in size, so putting it breaks our
invariants) and so we discard it.
The alternative would be to be pessimistic when moving data from
the pipe to the fold sink. I think this is worse because it would
make the code more complex.

Add some more Pipe tests.

---

okio/build.gradle

See https://kotlinlang.org/docs/reference/building-mpp-with-gradle.html#building-final-native-binaries

Use new Gradle DSL to configure Native outputs

---

okio/src/main/java/okio/PeekSource.java
okio/src/test/java/okio/BufferedSourceTest.java

The contract for read() is to return at least 1 byte, but we were
attempting to read the full request. That caused us to prematurely
do a blocking read on the upstream source.
This fixes that code to defer the blocking read.
Closes: https://github.com/square/okio/issues/594

Peek the minimum number of bytes to return a result (1.x branch)

---

README.md

Update README.md - fix broken proguard link

---

.buildscript/deploy_snapshot.sh

Note: this will publish snapshots for all targets

Fix snapshot publishing command

---

okio/src/jvmTest/kotlin/okio/ThrottlerTest.kt

Unblocks #601, tracking flakiness issues in #607

@Ignore flaky ThrottlerTest

---

okio/jvm/jmh/build.gradle
okio/jvm/jmh/src/jmh/java/com/squareup/okio/benchmarks/WriteHexadecimalBenchmark.java
okio/src/commonMain/kotlin/okio/internal/Buffer.kt
okio/src/jsMain/kotlin/okio/Buffer.kt
okio/src/jvmMain/kotlin/okio/Buffer.kt
okio/src/jvmTest/java/okio/BufferedSinkTest.java
okio/src/nativeMain/kotlin/okio/Buffer.kt

Found a couple algorithms on http://aggregate.org/MAGIC which were very helpful in replacing the Java specific methods for calculating the width required for a hex unsigned long. I'm hoping these are safe to use? I've linked the specific algorithm in the code.

Kotlin/Common Buffer read and write hexadecimal unsigned long

---

okio/src/jvmMain/kotlin/okio/-DeprecatedOkio.kt
okio/src/jvmMain/kotlin/okio/-DeprecatedUtf8.kt

Otherwise they show up in the docs.

Deprecate deprecate things.

---

build.gradle
gradle/gradle-mvn-mpp-push.gradle
okio/src/commonMain/kotlin/okio/Buffer.kt
okio/src/jsMain/kotlin/okio/Buffer.kt
okio/src/jsMain/kotlin/okio/ByteString.kt
okio/src/jsMain/kotlin/okio/SegmentedByteString.kt
okio/src/jvmMain/kotlin/okio/Buffer.kt
okio/src/jvmMain/kotlin/okio/ByteString.kt
okio/src/jvmMain/kotlin/okio/SegmentedByteString.kt
okio/src/nativeMain/kotlin/okio/Buffer.kt
okio/src/nativeMain/kotlin/okio/ByteString.kt
okio/src/nativeMain/kotlin/okio/SegmentedByteString.kt

https://github.com/Kotlin/dokka/releases/tag/0.10.0

Dokka 0.10.0

---

okio/src/jvmTest/kotlin/okio/TestUtil.kt

This was in my working directory. /shrug

Use Kotlin-isms for converting an array to a string

---

README.md

I found out that some people aren't that experienced with Gradle and don't know how to add the snapshot version to their project.
Therefore I've a little bit modified the section which gives the users a small hint how to add it.

Add how to use snapshot section to readme

---

okio/src/jvmMain/kotlin/okio/Buffer.kt
okio/src/jvmMain/kotlin/okio/Okio.kt
okio/src/jvmTest/java/okio/BufferTest.java
okio/src/jvmTest/java/okio/OkioTest.java
okio/src/jvmTest/kotlin/okio/TestUtil.kt

Remove empty tail Segment

---

build.gradle

Changelog: https://github.com/JetBrains/kotlin/blob/1.3.70/ChangeLog.md

Kotlin 1.3.70

---

okio/src/commonMain/kotlin/okio/Segment.kt

comment on var limit

---

.github/workflows/build.yml

Copied from https://github.com/cashapp/sqldelight/commit/6e7733a1170e434f8cfc84baf294716cfd458c9c

Update publish-website action to use a different plugin

---

okio/src/commonMain/kotlin/okio/Buffer.kt
okio/src/commonMain/kotlin/okio/internal/Buffer.kt
okio/src/commonTest/kotlin/okio/UnsafeCursorTest.kt
okio/src/jvmMain/kotlin/okio/Buffer.kt
okio/src/nonJvmMain/kotlin/okio/Buffer.kt

I want to use this in okio-files.

Promote UnsafeCursor to multiplatform

---

.editorconfig
okio/build.gradle

This was an oversight and is a follow up of #821 and #820

Added the watchosArm32 target.

---

build.gradle

Kotlin 1.4.20

---

okio/src/jvmMain/kotlin/okio/SegmentPool.kt

Since this type's creation, I had it on my TODO to study the impl, so
that I could love it for good reason. I've added some notes which might
help others love it faster.

Adds notes to SegmentPool

---

okio-files/src/commonMain/kotlin/okio/Path.kt
okio-files/src/commonTest/kotlin/okio/files/PathTest.kt

Also improve the structure of the path tests.

Fix some bugs in Windows path handling

---

okio-testing/src/commonMain/kotlin/okio/FakeFilesystem.kt
okio-testing/src/commonMain/kotlin/okio/time.kt
okio/build.gradle
okio/src/appleMain/kotlin/okio/posixVariant.kt
okio/src/commonMain/kotlin/okio/ExperimentalFilesystem.kt
okio/src/commonMain/kotlin/okio/FileMetadata.kt
okio/src/commonMain/kotlin/okio/Filesystem.kt
okio/src/commonMain/kotlin/okio/Path.kt
okio/src/commonMain/kotlin/okio/Platform.kt
okio/src/commonTest/kotlin/okio/AbstractFilesystemTest.kt
okio/src/commonTest/kotlin/okio/FakeFilesystemTest.kt
okio/src/commonTest/kotlin/okio/PathTest.kt
okio/src/commonTest/kotlin/okio/SystemFilesystemTest.kt
okio/src/commonTest/kotlin/okio/time.kt
okio/src/jsMain/kotlin/okio/NodeJsSystemFilesystem.kt
okio/src/jsMain/kotlin/okio/Platform.kt
okio/src/jvmMain/kotlin/okio/JvmSystemFilesystem.kt
okio/src/jvmMain/kotlin/okio/Paths.kt
okio/src/jvmMain/kotlin/okio/Platform.kt
okio/src/jvmTest/kotlin/okio/JvmTest.kt
okio/src/linuxX64Main/kotlin/okio/posixVariant.kt
okio/src/mingwX64Main/kotlin/okio/Platform.kt
okio/src/mingwX64Main/kotlin/okio/posixVariant.kt
okio/src/nativeMain/kotlin/okio/Platform.kt
okio/src/nativeMain/kotlin/okio/PosixSystemFilesystem.kt
okio/src/nativeMain/kotlin/okio/posixVariant.kt
okio/src/unixMain/kotlin/okio/posixVariant.kt

Instructions on opting-in are here:
https://kotlinlang.org/docs/reference/opt-in-requirements.html

Use @ExperimentalFilesystem on Filesystem, Path, and FileMetadata

---

android-test/README.md
android-test/build.gradle
android-test/multidex-config.pro
android-test/src/main/AndroidManifest.xml
build.gradle
docs/index.md
okio/jvm/jvm.gradle
okio/src/jvmMain/kotlin/okio/JvmSystemFilesystem.kt
okio/src/jvmMain/kotlin/okio/NioSystemFilesystem.kt
okio/src/jvmMain/kotlin/okio/Platform.kt

There is no java.nio.file until API 26 (Android 8.0).

Get Filesystem.SYSTEM working on Android 15

---

okio/src/commonMain/kotlin/okio/Path.kt

https://github.com/Kotlin/dokka/issues/1683

Use HTML tables until Dokka's tables are fixed

---

okio/src/commonMain/kotlin/okio/Path.kt
okio/src/commonMain/kotlin/okio/internal/Path.kt
okio/src/jvmMain/kotlin/okio/Path.kt
okio/src/nativeMain/kotlin/okio/PosixFileSystem.kt
okio/src/nonJvmMain/kotlin/okio/Path.kt
okio/src/unixMain/kotlin/okio/posixVariant.kt

I want to move methods into Path to make use from Java nicer.

Split Path into an expect/actual class

---

okio-zipfilesystem/src/jvmMain/kotlin/okio/zipfilesystem/ZipEntry.kt
okio-zipfilesystem/src/jvmMain/kotlin/okio/zipfilesystem/ZipFileSystem.kt
okio-zipfilesystem/src/jvmMain/kotlin/okio/zipfilesystem/zip.kt
okio-zipfilesystem/src/jvmTest/kotlin/okio/zipfilesystem/ZipFileSystemTest.kt

Import ZIP code from AOSP and use it to build a ZipFileSystem

---

okio/src/jvmTest/java/okio/SocketTimeoutTest.java

It's failing with a ConnectException

Attempt to fix flakes in SocketTimeoutTest

---

docs/multiplatform.md

It took me some time to figure out how to use okio multipllatform in my project, so I figured out I can help a bit with the documentation
Used here https://github.com/jmfayard/kotlin-cli-starter/commit/a035c26acec04d2e99af3304577c60af3051e4d5

multiplatform: document Gradle configuration

---

build.gradle.kts

We've got some tests failing in CI only and it's an extra step to figure
out what's actually broken.

Increase test logging

---

okio/src/commonTest/kotlin/okio/AbstractFileSystemTest.kt
okio/src/jvmMain/kotlin/okio/JvmFileHandle.kt

I didn't add enough initially, particularly around happy paths
on flush and position.

More tests for FileHandle

---

okio/src/jvmMain/kotlin/okio/FileSystem.kt
okio/src/jvmMain/kotlin/okio/JvmOkio.kt
okio/src/jvmMain/kotlin/okio/internal/ResourceFileSystem.kt
okio/src/jvmTest/java/okio/internal/ResourceFileSystemTest.kt

Previously, ResourceFileSystem.SYSTEM_RESOURCES, now FileSystem.RESOURCES.

Change how ResourceFileSystem is exposed

---

okio/src/commonMain/kotlin/okio/FileHandle.kt
okio/src/commonTest/kotlin/okio/AbstractFileSystemTest.kt

The one fancy thing we're doing here is preserving the buffered data if
we're seeking forward on a source.
I don't think there's a compelling equivalent for preserving buffered
data when seeking backwards on a sink. In theory we could truncate the
buffer to the new seek position, but this breaks if the writer doesn't
overwrite the full range of what was truncated.

APIs to seek a FileHandle's source or sink

---

okio/src/jvmMain/kotlin/okio/internal/ResourceFileSystem.kt
okio/src/jvmTest/java/okio/internal/ResourceFileSystemTest.kt

Previously ResourceFileSystem delegated most operations to the
ClassLoader on-demand. Now it eagerly computes a set of base paths
and then unions them.

Change ResourceFileSystem to load roots eagerly

---

build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/okio-publishing.gradle.kts
docs/css/dokka-logo.css
mkdocs.yml
okio-fakefilesystem/build.gradle.kts
okio-nodefilesystem/build.gradle.kts
okio/build.gradle.kts

Nothing was generated due to this issue: https://github.com/Kotlin/dokka/issues/1463

Fix Dokka generation

---

.github/workflows/build.yml

See [Bump setup-java action to v2](https://github.com/square/moshi/pull/1375).

Bump setup-java action to v2

---

.github/workflows/build.yml

See [Disable publish action in forked repository](https://github.com/square/kotlinpoet/pull/1119).

Disable publish actions in forked repository

---

build.gradle.kts
buildSrc/build.gradle.kts
okio-fakefilesystem/build.gradle.kts
okio-nodefilesystem/build.gradle.kts
okio/build.gradle.kts

- Replace deprecated methods.
- Merge `allprojects`.

Simplify kts

---

buildSrc/src/main/kotlin/Dependencies.kt

https://github.com/Kotlin/kotlinx-datetime/blob/master/CHANGELOG.md#030

Upgrade to datetime 0.3.0

---

okio/src/commonMain/kotlin/okio/Path.kt
okio/src/commonMain/kotlin/okio/internal/-Path.kt
okio/src/commonTest/kotlin/okio/PathTest.kt
okio/src/jvmMain/kotlin/okio/Path.kt
okio/src/nonJvmMain/kotlin/okio/Path.kt

This should make it easier to build useful stuff on top of paths.
Like relativeTo().

New API: Path.root and Path.segments

---

.github/workflows/build.yml
okio-nodefilesystem/src/main/kotlin/okio/NodeJsFileSystem.kt
okio/src/nativeMain/kotlin/okio/-PosixVariant.kt

Adds Linux host to run native tests

---

okio-fakefilesystem/src/commonMain/kotlin/okio/fakefilesystem/FakeFileSystem.kt
okio-fakefilesystem/src/commonMain/kotlin/okio/fakefilesystem/time.kt
okio/src/commonMain/kotlin/okio/FileMetadata.kt
okio/src/commonTest/kotlin/okio/FakeFileSystemTest.kt

I don't have a use case now but it's much easier to add the mechanism
now than later.
Closes: https://github.com/square/okio/issues/1005

Extensible metadata

---

build.gradle.kts

See square/leakcanary/pull/2234.

Publish to S01

---

docs/index.md
docs/releasing.md

Left overs from https://github.com/square/okio/pull/1077

Update sonatype urls to s01

---

okio/build.gradle.kts
okio/src/commonMain/kotlin/okio/-Util.kt
okio/src/commonMain/kotlin/okio/ByteString.kt
okio/src/commonMain/kotlin/okio/internal/-ByteString.kt
okio/src/commonTest/kotlin/okio/ByteStringMoreTests.kt

To fix https://github.com/square/okio/issues/1081

Fix for ByteString default param in JS.

---

okio-testing-support/src/commonMain/kotlin/okio/AbstractFileSystemTest.kt

Some FileSystem tests with special character named files

---

okio/src/jvmMain/kotlin/okio/CipherSink.kt
okio/src/jvmMain/kotlin/okio/CipherSource.kt

Hacky fix for #1093 to have a fallback implementation when the standard behavior fails.
There's unfortunately not tests to validate the bug fix. The two possibilities for it that I see would be:
1. Somehow, likely using a mocking framework to re-recreate the buggy `Cipher` behavior on the JVM, by caching all the  data provided to the instance through `update`, until `doFinal` is called
2. Set up tests on an Android emulator, somehow

Provide fallback for broken AES/GCM streaming implementation on Android

---

okio/src/jvmMain/kotlin/okio/SegmentPool.kt

"Acquire" LOCK for recycle() instead of using compareAndSet(). This
avoids an ABA problem. This change increases the number of atomic writes
during recycle() from 1 to 2, but doesn't really influence the
concurrency level.
ThreadSanitizer detected a race on the JVM for `Segment.limit` with okio
3.1. The write is setting `limit = 0` and the read is computing the pool
size.
```
WARNING: ThreadSanitizer: data race (pid=823)
Write of size 4 at 0x0000cea2e4f0 by thread T27:
#0 okio.SegmentPool.take()Lokio/Segment; SegmentPool.kt:94
#1 okio.Buffer.writableSegment$(I)Lokio/Segment; Buffer.kt:1444
#2 okio.InputStreamSource.read(Lokio/Buffer;J)J JvmOkio.kt:92
#3 okio.AsyncTimeout$source$1.read(Lokio/Buffer;J)J AsyncTimeout.kt:125
#4 okio.RealBufferedSource.request(J)Z RealBufferedSource.kt:206
#5 …
```

Fix ABA race in JVM SegmentPool

---

renovate.json

Turn off semantic commits explicitly in Renovate

---

.editorconfig
build.gradle.kts

Also use Redwood's .editorconfig content and layout

Get style from .editorconfig

---

renovate.json

Fix renovate settings

---

okio-fakefilesystem/src/commonMain/kotlin/okio/fakefilesystem/FakeFileSystem.kt
okio-testing-support/src/commonMain/kotlin/okio/AbstractFileSystemTest.kt

Closes: https://github.com/square/okio/issues/1229

Make FakeFileSystem.canonicalize resolve symlinks

---

okio-testing-support/src/commonMain/kotlin/okio/AbstractFileSystemTest.kt

leftovers from the early days?

Remove maybe obsolete check?

---

build.gradle.kts
gradle/libs.versions.toml
gradle/wrapper/gradle-wrapper.properties
okio/jvm/jmh/build.gradle.kts

JMH configuration is much easier now.

Upgrade Gradle and JMH

---

build-support/src/main/kotlin/BuildSupport.kt
build-support/src/main/kotlin/bom.kt
build-support/src/main/kotlin/jvm.kt
build-support/src/main/kotlin/kmp.kt
build-support/src/main/kotlin/platforms.kt

Copyright to files in build-support

---

docs/index.md

Closes: https://github.com/square/okio/issues/1302

We don't need a .pro file any more

---

.github/workflows/build.yml

I believe it's ready.
This reverts commit 1be462186eef7753acab9fcea39b246943d60d2c.

Restore wasm to the publish job

---

okio/src/jvmMain/kotlin/okio/internal/ResourceFileSystem.kt
okio/src/jvmTest/kotlin/okio/internal/ResourceFileSystemTest.kt

Closes: https://github.com/square/okio/issues/1347

Make ResourceFileSystem.read lazy

---

docs/index.md

https://www.youtube.com/watch?v=Du7YXPAV1M8

Add "Nerding Out On Okio" video to the docs

---

okio/src/jvmTest/kotlin/okio/FileLeakTest.kt

Test for #1331
It seems this bug only occurs if the zip file has a directory structure that leads to the internal `symlinkTarget` extension function, which hits `metadata` of the `ZipFileSystem`. #1359 was the cause for this issue, and the test added was tested before and after the fix to confirm it captures the issue.
This PR also has some cleanup of the tests.

Test for listRecursively causing delete to fail

---

okio/src/jvmMain/kotlin/okio/Timeout.kt

Support Duration in Timeout

---

okio/api/okio.api

Run apiDump

---

okio/src/nativeMain/kotlin/okio/DataProcessor.kt
okio/src/nativeMain/kotlin/okio/Deflater.kt
okio/src/nativeMain/kotlin/okio/Inflater.kt
okio/src/nativeTest/kotlin/okio/DeflaterTest.kt
okio/src/nativeTest/kotlin/okio/InflaterTest.kt

I expect this to simplify adding DeflaterSink and InflaterSource.

Make Inflater and Deflater symmetric

---

okio/build.gradle.kts
okio/src/jvmMain/kotlin/okio/internal/-ZlibJvm.kt
okio/src/nativeMain/kotlin/okio/internal/CRC32.kt
okio/src/zlibMain/kotlin/okio/internal/CRC32.kt
okio/src/zlibTest/kotlin/okio/internal/CRC32Test.kt

On Kotlin/Native this uses the built-in zlib

Implement CRC32

---

okio/src/commonMain/kotlin/okio/internal/RealBufferedSource.kt
okio/src/commonTest/kotlin/okio/AbstractBufferedSourceTest.kt
okio/src/commonTest/kotlin/okio/CommonRealBufferedSourceTest.kt
okio/src/jvmTest/kotlin/okio/BufferedSourceTest.kt

Closes: https://github.com/square/okio/issues/1476

Don't block on 0-byte reads

---

docs/recipes.md

PR #1035 renamed the `ReadFileLineByLine.kt` file to be `ReadJavaIoFileLineByLine.kt`. This PR adjusts sources to changes.

Update ReadFileLineByLineKt reference

---

settings.gradle.kts

See https://developer.android.com/tools/variables#envar

Use modern env var for Android detection

---

okio/jvm/jmh/src/jmh/java/com/squareup/okio/benchmarks/AsyncTimeoutBenchmark.java
okio/src/jvmMain/kotlin/okio/AsyncTimeout.kt
okio/src/jvmTest/kotlin/okio/internal/MinHeapTest.kt

- Don't sample clock too much. 
- Use array representation to manage heap.

Heap improvements. 

---

gradle/libs.versions.toml
kotlin-js-store/yarn.lock
okio-wasifilesystem/build.gradle.kts

Also Burst 2.6.0
Closes: https://github.com/square/okio/issues/1632

Upgrade to Kotlin 2.2.0
